-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity create_tree is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_value_V_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    in_value_V_empty_n : IN STD_LOGIC;
    in_value_V_read : OUT STD_LOGIC;
    in_frequency_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    in_frequency_V_empty_n : IN STD_LOGIC;
    in_frequency_V_read : OUT STD_LOGIC;
    extLd_loc_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    extLd_loc_empty_n : IN STD_LOGIC;
    extLd_loc_read : OUT STD_LOGIC;
    parent_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    parent_V_ce0 : OUT STD_LOGIC;
    parent_V_we0 : OUT STD_LOGIC;
    parent_V_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    left_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    left_V_ce0 : OUT STD_LOGIC;
    left_V_we0 : OUT STD_LOGIC;
    left_V_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    right_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    right_V_ce0 : OUT STD_LOGIC;
    right_V_we0 : OUT STD_LOGIC;
    right_V_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    extLd_loc_out_din : OUT STD_LOGIC_VECTOR (8 downto 0);
    extLd_loc_out_full_n : IN STD_LOGIC;
    extLd_loc_out_write : OUT STD_LOGIC );
end;


architecture behav of create_tree is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_value_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln21_reg_766 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln34_reg_806 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal or_ln52_reg_840 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_frequency_V_blk_n : STD_LOGIC;
    signal extLd_loc_blk_n : STD_LOGIC;
    signal extLd_loc_out_blk_n : STD_LOGIC;
    signal extLd_loc_read_reg_734 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal s_value_V_reg_741 : STD_LOGIC_VECTOR (8 downto 0);
    signal s_frequency_V_reg_746 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal add_ln21_fu_500_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln21_reg_761 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln21_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_fu_515_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_reg_770 : STD_LOGIC_VECTOR (8 downto 0);
    signal intermediate_freq_V_1_fu_572_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal intermediate_freq_V_1_reg_795 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal intermediate_freq_ne_fu_580_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal intermediate_freq_ne_reg_801 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln34_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln36_fu_623_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln36_reg_810 : STD_LOGIC_VECTOR (63 downto 0);
    signal tree_count_V_fu_628_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_predicate_op78_read_state5 : BOOLEAN;
    signal ap_predicate_op79_read_state5 : BOOLEAN;
    signal ap_block_state5 : BOOLEAN;
    signal in_count_V_fu_634_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal right_V_addr_reg_835 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln52_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tree_count_V_1_fu_698_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal frequency_0_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal frequency_0_V_ce0 : STD_LOGIC;
    signal frequency_0_V_we0 : STD_LOGIC;
    signal frequency_0_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal frequency_0_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal frequency_0_V_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal frequency_0_V_ce1 : STD_LOGIC;
    signal frequency_0_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal frequency_1_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal frequency_1_V_ce0 : STD_LOGIC;
    signal frequency_1_V_we0 : STD_LOGIC;
    signal frequency_1_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal frequency_1_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal frequency_1_V_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal frequency_1_V_ce1 : STD_LOGIC;
    signal frequency_1_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_frequency_V_1_reg_245 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_op127_read_state7 : BOOLEAN;
    signal ap_predicate_op128_read_state7 : BOOLEAN;
    signal ap_block_state7 : BOOLEAN;
    signal s_value_V_1_reg_255 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal node_freq_V_reg_265 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_s_1_2_i_i_phi_fu_441_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_0_0_i_i_reg_275 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_mux_s_0_2_i_i_phi_fu_454_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal t_V_2_reg_286 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal t_V_reg_298 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal op_assign_reg_310 : STD_LOGIC_VECTOR (8 downto 0);
    signal s_frequency_V_2_reg_323 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_value_V_2_reg_334 : STD_LOGIC_VECTOR (8 downto 0);
    signal s_1_1_i_i_reg_345 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_0_1_i_i_reg_357 : STD_LOGIC_VECTOR (8 downto 0);
    signal t_V_4_reg_370 : STD_LOGIC_VECTOR (8 downto 0);
    signal t_V_3_reg_381 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_0195_0_i_i_reg_392 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0120_0_i_i_reg_402 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_next_1_2_i_i_reg_411 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_next_0_2_i_i_reg_424 : STD_LOGIC_VECTOR (8 downto 0);
    signal s_1_2_i_i_reg_437 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_0_2_i_i_reg_450 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_0217_2_i_i_reg_463 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_count_V_1_fu_722_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_0247_2_i_i_reg_475 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln31_fu_531_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_fu_557_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_fu_563_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln321_1_fu_687_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_4_fu_693_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln321_fu_716_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_3_fu_729_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal trunc_ln321_1_fu_683_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln209_1_fu_675_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln321_fu_712_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln209_fu_704_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal extLd_cast_fu_497_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln243_fu_506_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln_fu_521_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_fu_537_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ret_V_fu_541_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln1_fu_547_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln31_fu_568_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_1_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln34_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln52_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_fu_657_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_3_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_487_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_184 : BOOLEAN;

    component create_tree_frequhbi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component create_tree_frequibs IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    frequency_0_V_U : component create_tree_frequhbi
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => frequency_0_V_address0,
        ce0 => frequency_0_V_ce0,
        we0 => frequency_0_V_we0,
        d0 => frequency_0_V_d0,
        q0 => frequency_0_V_q0,
        address1 => frequency_0_V_address1,
        ce1 => frequency_0_V_ce1,
        q1 => frequency_0_V_q1);

    frequency_1_V_U : component create_tree_frequibs
    generic map (
        DataWidth => 32,
        AddressRange => 127,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => frequency_1_V_address0,
        ce0 => frequency_1_V_ce0,
        we0 => frequency_1_V_we0,
        d0 => frequency_1_V_d0,
        q0 => frequency_1_V_q0,
        address1 => frequency_1_V_address1,
        ce1 => frequency_1_V_ce1,
        q1 => frequency_1_V_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    node_freq_V_reg_265_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                node_freq_V_reg_265 <= ap_phi_mux_s_1_2_i_i_phi_fu_441_p4;
            elsif ((not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                node_freq_V_reg_265 <= s_frequency_V_reg_746;
            end if; 
        end if;
    end process;

    op_assign_reg_310_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                op_assign_reg_310 <= i_reg_770;
            elsif ((not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                op_assign_reg_310 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    p_0120_0_i_i_reg_402_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if ((or_ln34_reg_806 = ap_const_lv1_0)) then 
                    p_0120_0_i_i_reg_402 <= intermediate_freq_ne_reg_801;
                elsif ((or_ln34_reg_806 = ap_const_lv1_1)) then 
                    p_0120_0_i_i_reg_402 <= intermediate_freq_V_1_reg_795;
                end if;
            end if; 
        end if;
    end process;

    p_0195_0_i_i_reg_392_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if ((or_ln34_reg_806 = ap_const_lv1_0)) then 
                    p_0195_0_i_i_reg_392 <= intermediate_freq_V_1_reg_795;
                elsif ((or_ln34_reg_806 = ap_const_lv1_1)) then 
                    p_0195_0_i_i_reg_392 <= node_freq_V_reg_265;
                end if;
            end if; 
        end if;
    end process;

    p_0217_2_i_i_reg_463_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
                p_0217_2_i_i_reg_463 <= tree_count_V_1_fu_698_p2;
            elsif ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                p_0217_2_i_i_reg_463 <= t_V_4_reg_370;
            end if; 
        end if;
    end process;

    p_0247_2_i_i_reg_475_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
                p_0247_2_i_i_reg_475 <= t_V_3_reg_381;
            elsif ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                p_0247_2_i_i_reg_475 <= in_count_V_1_fu_722_p2;
            end if; 
        end if;
    end process;

    s_0_0_i_i_reg_275_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                s_0_0_i_i_reg_275 <= ap_phi_mux_s_0_2_i_i_phi_fu_454_p4;
            elsif ((not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                s_0_0_i_i_reg_275 <= s_value_V_reg_741;
            end if; 
        end if;
    end process;

    s_0_1_i_i_reg_357_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if ((or_ln34_reg_806 = ap_const_lv1_0)) then 
                    s_0_1_i_i_reg_357 <= s_0_0_i_i_reg_275;
                elsif ((or_ln34_reg_806 = ap_const_lv1_1)) then 
                    s_0_1_i_i_reg_357 <= s_value_V_1_reg_255;
                end if;
            end if; 
        end if;
    end process;

    s_0_2_i_i_reg_450_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
                s_0_2_i_i_reg_450 <= s_0_1_i_i_reg_357;
            elsif ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                s_0_2_i_i_reg_450 <= s_value_V_2_reg_334;
            end if; 
        end if;
    end process;

    s_1_1_i_i_reg_345_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if ((or_ln34_reg_806 = ap_const_lv1_0)) then 
                    s_1_1_i_i_reg_345 <= node_freq_V_reg_265;
                elsif ((or_ln34_reg_806 = ap_const_lv1_1)) then 
                    s_1_1_i_i_reg_345 <= s_frequency_V_1_reg_245;
                end if;
            end if; 
        end if;
    end process;

    s_1_2_i_i_reg_437_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
                s_1_2_i_i_reg_437 <= s_1_1_i_i_reg_345;
            elsif ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                s_1_2_i_i_reg_437 <= s_frequency_V_2_reg_323;
            end if; 
        end if;
    end process;

    s_frequency_V_1_reg_245_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                s_frequency_V_1_reg_245 <= ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4;
            elsif ((not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                s_frequency_V_1_reg_245 <= in_frequency_V_dout;
            end if; 
        end if;
    end process;

    s_frequency_V_2_reg_323_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if ((or_ln34_reg_806 = ap_const_lv1_0)) then 
                    s_frequency_V_2_reg_323 <= s_frequency_V_1_reg_245;
                elsif ((or_ln34_reg_806 = ap_const_lv1_1)) then 
                    s_frequency_V_2_reg_323 <= in_frequency_V_dout;
                end if;
            end if; 
        end if;
    end process;

    s_next_0_2_i_i_reg_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
                s_next_0_2_i_i_reg_424 <= s_value_V_2_reg_334;
            elsif ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                s_next_0_2_i_i_reg_424 <= in_value_V_dout;
            end if; 
        end if;
    end process;

    s_next_1_2_i_i_reg_411_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
                s_next_1_2_i_i_reg_411 <= s_frequency_V_2_reg_323;
            elsif ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                s_next_1_2_i_i_reg_411 <= in_frequency_V_dout;
            end if; 
        end if;
    end process;

    s_value_V_1_reg_255_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                s_value_V_1_reg_255 <= ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4;
            elsif ((not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                s_value_V_1_reg_255 <= in_value_V_dout;
            end if; 
        end if;
    end process;

    s_value_V_2_reg_334_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if ((or_ln34_reg_806 = ap_const_lv1_0)) then 
                    s_value_V_2_reg_334 <= s_value_V_1_reg_255;
                elsif ((or_ln34_reg_806 = ap_const_lv1_1)) then 
                    s_value_V_2_reg_334 <= in_value_V_dout;
                end if;
            end if; 
        end if;
    end process;

    t_V_2_reg_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                t_V_2_reg_286 <= ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4;
            elsif ((not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_V_2_reg_286 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    t_V_3_reg_381_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if ((or_ln34_reg_806 = ap_const_lv1_0)) then 
                    t_V_3_reg_381 <= t_V_reg_298;
                elsif ((or_ln34_reg_806 = ap_const_lv1_1)) then 
                    t_V_3_reg_381 <= in_count_V_fu_634_p2;
                end if;
            end if; 
        end if;
    end process;

    t_V_4_reg_370_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if ((or_ln34_reg_806 = ap_const_lv1_0)) then 
                    t_V_4_reg_370 <= tree_count_V_fu_628_p2;
                elsif ((or_ln34_reg_806 = ap_const_lv1_1)) then 
                    t_V_4_reg_370 <= t_V_2_reg_286;
                end if;
            end if; 
        end if;
    end process;

    t_V_reg_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                t_V_reg_298 <= ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4;
            elsif ((not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_V_reg_298 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln21_reg_761 <= add_ln21_fu_500_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((extLd_loc_out_full_n = ap_const_logic_0) or (extLd_loc_empty_n = ap_const_logic_0) or (in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                extLd_loc_read_reg_734 <= extLd_loc_dout;
                s_frequency_V_reg_746 <= in_frequency_V_dout;
                s_value_V_reg_741 <= in_value_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                i_reg_770 <= i_fu_515_p2;
                icmp_ln21_reg_766 <= icmp_ln21_fu_510_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                intermediate_freq_V_1_reg_795 <= intermediate_freq_V_1_fu_572_p3;
                intermediate_freq_ne_reg_801 <= intermediate_freq_ne_fu_580_p3;
                or_ln34_reg_806 <= or_ln34_fu_617_p2;
                    zext_ln36_reg_810(8 downto 0) <= zext_ln36_fu_623_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                or_ln52_reg_840 <= or_ln52_fu_669_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op79_read_state5 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op78_read_state5 = ap_const_boolean_1)))) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                right_V_addr_reg_835 <= zext_ln36_reg_810(8 - 1 downto 0);
            end if;
        end if;
    end process;
    zext_ln36_reg_810(63 downto 9) <= "0000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, in_value_V_empty_n, in_frequency_V_empty_n, extLd_loc_empty_n, extLd_loc_out_full_n, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state7, icmp_ln21_fu_510_p2, ap_CS_fsm_state3, ap_predicate_op78_read_state5, ap_predicate_op79_read_state5, ap_predicate_op127_read_state7, ap_predicate_op128_read_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((extLd_loc_out_full_n = ap_const_logic_0) or (extLd_loc_empty_n = ap_const_logic_0) or (in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln21_fu_510_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op79_read_state5 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op78_read_state5 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if ((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln209_1_fu_675_p2 <= std_logic_vector(unsigned(p_0195_0_i_i_reg_392) + unsigned(p_0120_0_i_i_reg_402));
    add_ln209_fu_704_p2 <= std_logic_vector(unsigned(p_0195_0_i_i_reg_392) + unsigned(s_1_1_i_i_reg_345));
    add_ln21_fu_500_p2 <= std_logic_vector(unsigned(extLd_cast_fu_497_p1) + unsigned(ap_const_lv10_3FF));
    and_ln34_fu_605_p2 <= (xor_ln34_fu_599_p2 and icmp_ln34_fu_588_p2);
    and_ln52_fu_657_p2 <= (xor_ln52_fu_651_p2 and icmp_ln52_fu_640_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, in_value_V_empty_n, in_frequency_V_empty_n, extLd_loc_empty_n, extLd_loc_out_full_n)
    begin
                ap_block_state1 <= ((extLd_loc_out_full_n = ap_const_logic_0) or (extLd_loc_empty_n = ap_const_logic_0) or (in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(in_value_V_empty_n, in_frequency_V_empty_n)
    begin
                ap_block_state2 <= ((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_assign_proc : process(in_value_V_empty_n, in_frequency_V_empty_n, ap_predicate_op78_read_state5, ap_predicate_op79_read_state5)
    begin
                ap_block_state5 <= (((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op79_read_state5 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op78_read_state5 = ap_const_boolean_1)));
    end process;


    ap_block_state7_assign_proc : process(in_value_V_empty_n, in_frequency_V_empty_n, ap_predicate_op127_read_state7, ap_predicate_op128_read_state7)
    begin
                ap_block_state7 <= (((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)));
    end process;


    ap_condition_184_assign_proc : process(in_value_V_empty_n, in_frequency_V_empty_n, ap_CS_fsm_state5, icmp_ln21_reg_766, ap_predicate_op78_read_state5, ap_predicate_op79_read_state5)
    begin
                ap_condition_184 <= (not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op79_read_state5 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op78_read_state5 = ap_const_boolean_1)))) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4_assign_proc : process(icmp_ln21_reg_766, ap_CS_fsm_state7, or_ln52_reg_840, t_V_4_reg_370, p_0217_2_i_i_reg_463)
    begin
        if (((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4 <= t_V_4_reg_370;
        else 
            ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4 <= p_0217_2_i_i_reg_463;
        end if; 
    end process;


    ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4_assign_proc : process(icmp_ln21_reg_766, ap_CS_fsm_state7, or_ln52_reg_840, in_count_V_1_fu_722_p2, p_0247_2_i_i_reg_475)
    begin
        if (((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4 <= in_count_V_1_fu_722_p2;
        else 
            ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4 <= p_0247_2_i_i_reg_475;
        end if; 
    end process;


    ap_phi_mux_s_0_2_i_i_phi_fu_454_p4_assign_proc : process(icmp_ln21_reg_766, ap_CS_fsm_state7, or_ln52_reg_840, s_value_V_2_reg_334, s_0_2_i_i_reg_450)
    begin
        if (((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_phi_mux_s_0_2_i_i_phi_fu_454_p4 <= s_value_V_2_reg_334;
        else 
            ap_phi_mux_s_0_2_i_i_phi_fu_454_p4 <= s_0_2_i_i_reg_450;
        end if; 
    end process;


    ap_phi_mux_s_1_2_i_i_phi_fu_441_p4_assign_proc : process(icmp_ln21_reg_766, ap_CS_fsm_state7, or_ln52_reg_840, s_frequency_V_2_reg_323, s_1_2_i_i_reg_437)
    begin
        if (((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_phi_mux_s_1_2_i_i_phi_fu_441_p4 <= s_frequency_V_2_reg_323;
        else 
            ap_phi_mux_s_1_2_i_i_phi_fu_441_p4 <= s_1_2_i_i_reg_437;
        end if; 
    end process;


    ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4_assign_proc : process(in_value_V_dout, icmp_ln21_reg_766, ap_CS_fsm_state7, or_ln52_reg_840, s_next_0_2_i_i_reg_424)
    begin
        if (((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4 <= in_value_V_dout;
        else 
            ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4 <= s_next_0_2_i_i_reg_424;
        end if; 
    end process;


    ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4_assign_proc : process(in_frequency_V_dout, icmp_ln21_reg_766, ap_CS_fsm_state7, or_ln52_reg_840, s_next_1_2_i_i_reg_411)
    begin
        if (((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4 <= in_frequency_V_dout;
        else 
            ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4 <= s_next_1_2_i_i_reg_411;
        end if; 
    end process;


    ap_predicate_op127_read_state7_assign_proc : process(icmp_ln21_reg_766, or_ln52_reg_840)
    begin
                ap_predicate_op127_read_state7 <= ((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1));
    end process;


    ap_predicate_op128_read_state7_assign_proc : process(icmp_ln21_reg_766, or_ln52_reg_840)
    begin
                ap_predicate_op128_read_state7 <= ((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1));
    end process;


    ap_predicate_op78_read_state5_assign_proc : process(icmp_ln21_reg_766, or_ln34_reg_806)
    begin
                ap_predicate_op78_read_state5 <= ((or_ln34_reg_806 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1));
    end process;


    ap_predicate_op79_read_state5_assign_proc : process(icmp_ln21_reg_766, or_ln34_reg_806)
    begin
                ap_predicate_op79_read_state5 <= ((or_ln34_reg_806 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    extLd_cast_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(extLd_loc_read_reg_734),10));

    extLd_loc_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, extLd_loc_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            extLd_loc_blk_n <= extLd_loc_empty_n;
        else 
            extLd_loc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    extLd_loc_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, extLd_loc_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            extLd_loc_out_blk_n <= extLd_loc_out_full_n;
        else 
            extLd_loc_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    extLd_loc_out_din <= extLd_loc_dout;

    extLd_loc_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, in_value_V_empty_n, in_frequency_V_empty_n, extLd_loc_empty_n, extLd_loc_out_full_n)
    begin
        if ((not(((extLd_loc_out_full_n = ap_const_logic_0) or (extLd_loc_empty_n = ap_const_logic_0) or (in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            extLd_loc_out_write <= ap_const_logic_1;
        else 
            extLd_loc_out_write <= ap_const_logic_0;
        end if; 
    end process;


    extLd_loc_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, in_value_V_empty_n, in_frequency_V_empty_n, extLd_loc_empty_n, extLd_loc_out_full_n)
    begin
        if ((not(((extLd_loc_out_full_n = ap_const_logic_0) or (extLd_loc_empty_n = ap_const_logic_0) or (in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            extLd_loc_read <= ap_const_logic_1;
        else 
            extLd_loc_read <= ap_const_logic_0;
        end if; 
    end process;


    frequency_0_V_address0_assign_proc : process(ap_CS_fsm_state3, or_ln52_fu_669_p2, ap_CS_fsm_state6, zext_ln31_fu_531_p1, zext_ln321_1_fu_687_p1, zext_ln321_fu_716_p1, trunc_ln321_1_fu_683_p1, trunc_ln321_fu_712_p1)
    begin
        if (((or_ln52_fu_669_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (trunc_ln321_fu_712_p1 = ap_const_lv1_0))) then 
            frequency_0_V_address0 <= zext_ln321_fu_716_p1(7 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (trunc_ln321_1_fu_683_p1 = ap_const_lv1_0) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
            frequency_0_V_address0 <= zext_ln321_1_fu_687_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            frequency_0_V_address0 <= zext_ln31_fu_531_p1(7 - 1 downto 0);
        else 
            frequency_0_V_address0 <= "XXXXXXX";
        end if; 
    end process;

    frequency_0_V_address1 <= zext_ln32_fu_557_p1(7 - 1 downto 0);

    frequency_0_V_ce0_assign_proc : process(ap_CS_fsm_state3, or_ln52_fu_669_p2, ap_CS_fsm_state6, trunc_ln321_1_fu_683_p1, trunc_ln321_fu_712_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((or_ln52_fu_669_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (trunc_ln321_fu_712_p1 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (trunc_ln321_1_fu_683_p1 = ap_const_lv1_0) and (or_ln52_fu_669_p2 = ap_const_lv1_0)))) then 
            frequency_0_V_ce0 <= ap_const_logic_1;
        else 
            frequency_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frequency_0_V_ce1_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            frequency_0_V_ce1 <= ap_const_logic_1;
        else 
            frequency_0_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    frequency_0_V_d0_assign_proc : process(or_ln52_fu_669_p2, ap_CS_fsm_state6, trunc_ln321_1_fu_683_p1, add_ln209_1_fu_675_p2, trunc_ln321_fu_712_p1, add_ln209_fu_704_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
            if (((or_ln52_fu_669_p2 = ap_const_lv1_1) and (trunc_ln321_fu_712_p1 = ap_const_lv1_0))) then 
                frequency_0_V_d0 <= add_ln209_fu_704_p2;
            elsif (((trunc_ln321_1_fu_683_p1 = ap_const_lv1_0) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
                frequency_0_V_d0 <= add_ln209_1_fu_675_p2;
            else 
                frequency_0_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            frequency_0_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    frequency_0_V_we0_assign_proc : process(or_ln52_fu_669_p2, ap_CS_fsm_state6, trunc_ln321_1_fu_683_p1, trunc_ln321_fu_712_p1)
    begin
        if ((((or_ln52_fu_669_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (trunc_ln321_fu_712_p1 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (trunc_ln321_1_fu_683_p1 = ap_const_lv1_0) and (or_ln52_fu_669_p2 = ap_const_lv1_0)))) then 
            frequency_0_V_we0 <= ap_const_logic_1;
        else 
            frequency_0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    frequency_1_V_address0_assign_proc : process(ap_CS_fsm_state3, or_ln52_fu_669_p2, ap_CS_fsm_state6, zext_ln31_fu_531_p1, zext_ln321_1_fu_687_p1, zext_ln321_fu_716_p1, trunc_ln321_1_fu_683_p1, trunc_ln321_fu_712_p1)
    begin
        if (((trunc_ln321_fu_712_p1 = ap_const_lv1_1) and (or_ln52_fu_669_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            frequency_1_V_address0 <= zext_ln321_fu_716_p1(7 - 1 downto 0);
        elsif (((trunc_ln321_1_fu_683_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
            frequency_1_V_address0 <= zext_ln321_1_fu_687_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            frequency_1_V_address0 <= zext_ln31_fu_531_p1(7 - 1 downto 0);
        else 
            frequency_1_V_address0 <= "XXXXXXX";
        end if; 
    end process;

    frequency_1_V_address1 <= zext_ln32_fu_557_p1(7 - 1 downto 0);

    frequency_1_V_ce0_assign_proc : process(ap_CS_fsm_state3, or_ln52_fu_669_p2, ap_CS_fsm_state6, trunc_ln321_1_fu_683_p1, trunc_ln321_fu_712_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((trunc_ln321_fu_712_p1 = ap_const_lv1_1) and (or_ln52_fu_669_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((trunc_ln321_1_fu_683_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0)))) then 
            frequency_1_V_ce0 <= ap_const_logic_1;
        else 
            frequency_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frequency_1_V_ce1_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            frequency_1_V_ce1 <= ap_const_logic_1;
        else 
            frequency_1_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    frequency_1_V_d0_assign_proc : process(or_ln52_fu_669_p2, ap_CS_fsm_state6, trunc_ln321_1_fu_683_p1, add_ln209_1_fu_675_p2, trunc_ln321_fu_712_p1, add_ln209_fu_704_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
            if (((trunc_ln321_fu_712_p1 = ap_const_lv1_1) and (or_ln52_fu_669_p2 = ap_const_lv1_1))) then 
                frequency_1_V_d0 <= add_ln209_fu_704_p2;
            elsif (((trunc_ln321_1_fu_683_p1 = ap_const_lv1_1) and (or_ln52_fu_669_p2 = ap_const_lv1_0))) then 
                frequency_1_V_d0 <= add_ln209_1_fu_675_p2;
            else 
                frequency_1_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            frequency_1_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    frequency_1_V_we0_assign_proc : process(or_ln52_fu_669_p2, ap_CS_fsm_state6, trunc_ln321_1_fu_683_p1, trunc_ln321_fu_712_p1)
    begin
        if ((((trunc_ln321_fu_712_p1 = ap_const_lv1_1) and (or_ln52_fu_669_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((trunc_ln321_1_fu_683_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0)))) then 
            frequency_1_V_we0 <= ap_const_logic_1;
        else 
            frequency_1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_487_p4 <= op_assign_reg_310(8 downto 1);
    i_fu_515_p2 <= std_logic_vector(unsigned(op_assign_reg_310) + unsigned(ap_const_lv9_1));
    icmp_ln21_fu_510_p2 <= "1" when (signed(zext_ln243_fu_506_p1) < signed(add_ln21_reg_761)) else "0";
    icmp_ln34_1_fu_593_p2 <= "1" when (unsigned(intermediate_freq_V_1_fu_572_p3) < unsigned(node_freq_V_reg_265)) else "0";
    icmp_ln34_fu_588_p2 <= "1" when (unsigned(t_V_reg_298) < unsigned(extLd_loc_read_reg_734)) else "0";
    icmp_ln52_1_fu_645_p2 <= "1" when (unsigned(p_0120_0_i_i_reg_402) < unsigned(s_1_1_i_i_reg_345)) else "0";
    icmp_ln52_fu_640_p2 <= "1" when (unsigned(t_V_3_reg_381) < unsigned(extLd_loc_read_reg_734)) else "0";
    icmp_ln879_3_fu_663_p2 <= "1" when (t_V_4_reg_370 = op_assign_reg_310) else "0";
    icmp_ln879_fu_611_p2 <= "1" when (t_V_2_reg_286 = op_assign_reg_310) else "0";
    in_count_V_1_fu_722_p2 <= std_logic_vector(unsigned(t_V_3_reg_381) + unsigned(ap_const_lv9_1));
    in_count_V_fu_634_p2 <= std_logic_vector(unsigned(t_V_reg_298) + unsigned(ap_const_lv9_1));

    in_frequency_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, in_frequency_V_empty_n, ap_CS_fsm_state2, ap_CS_fsm_state5, icmp_ln21_reg_766, or_ln34_reg_806, ap_CS_fsm_state7, or_ln52_reg_840)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((or_ln34_reg_806 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            in_frequency_V_blk_n <= in_frequency_V_empty_n;
        else 
            in_frequency_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_frequency_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, in_value_V_empty_n, in_frequency_V_empty_n, extLd_loc_empty_n, extLd_loc_out_full_n, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_predicate_op78_read_state5, ap_predicate_op79_read_state5, ap_predicate_op127_read_state7, ap_predicate_op128_read_state7)
    begin
        if (((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (ap_predicate_op128_read_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op79_read_state5 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op78_read_state5 = ap_const_boolean_1)))) and (ap_predicate_op79_read_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((extLd_loc_out_full_n = ap_const_logic_0) or (extLd_loc_empty_n = ap_const_logic_0) or (in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            in_frequency_V_read <= ap_const_logic_1;
        else 
            in_frequency_V_read <= ap_const_logic_0;
        end if; 
    end process;


    in_value_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, in_value_V_empty_n, ap_CS_fsm_state2, ap_CS_fsm_state5, icmp_ln21_reg_766, or_ln34_reg_806, ap_CS_fsm_state7, or_ln52_reg_840)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((or_ln52_reg_840 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((or_ln34_reg_806 = ap_const_lv1_1) and (icmp_ln21_reg_766 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            in_value_V_blk_n <= in_value_V_empty_n;
        else 
            in_value_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_value_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, in_value_V_empty_n, in_frequency_V_empty_n, extLd_loc_empty_n, extLd_loc_out_full_n, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_predicate_op78_read_state5, ap_predicate_op79_read_state5, ap_predicate_op127_read_state7, ap_predicate_op128_read_state7)
    begin
        if (((not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state7 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op127_read_state7 = ap_const_boolean_1)))) and (ap_predicate_op127_read_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not((((in_frequency_V_empty_n = ap_const_logic_0) and (ap_predicate_op79_read_state5 = ap_const_boolean_1)) or ((in_value_V_empty_n = ap_const_logic_0) and (ap_predicate_op78_read_state5 = ap_const_boolean_1)))) and (ap_predicate_op78_read_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((extLd_loc_out_full_n = ap_const_logic_0) or (extLd_loc_empty_n = ap_const_logic_0) or (in_frequency_V_empty_n = ap_const_logic_0) or (in_value_V_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            in_value_V_read <= ap_const_logic_1;
        else 
            in_value_V_read <= ap_const_logic_0;
        end if; 
    end process;

    intermediate_freq_V_1_fu_572_p3 <= 
        frequency_1_V_q0 when (trunc_ln31_fu_568_p1(0) = '1') else 
        frequency_0_V_q0;
    intermediate_freq_ne_fu_580_p3 <= 
        frequency_0_V_q1 when (trunc_ln31_fu_568_p1(0) = '1') else 
        frequency_1_V_q1;
    left_V_address0 <= zext_ln36_fu_623_p1(8 - 1 downto 0);

    left_V_ce0_assign_proc : process(ap_CS_fsm_state4, or_ln34_fu_617_p2)
    begin
        if ((((or_ln34_fu_617_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (or_ln34_fu_617_p2 = ap_const_lv1_0)))) then 
            left_V_ce0 <= ap_const_logic_1;
        else 
            left_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    left_V_d0_assign_proc : process(ap_CS_fsm_state4, or_ln34_fu_617_p2, s_0_0_i_i_reg_275)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((or_ln34_fu_617_p2 = ap_const_lv1_1)) then 
                left_V_d0 <= s_0_0_i_i_reg_275;
            elsif ((or_ln34_fu_617_p2 = ap_const_lv1_0)) then 
                left_V_d0 <= ap_const_lv9_1FF;
            else 
                left_V_d0 <= "XXXXXXXXX";
            end if;
        else 
            left_V_d0 <= "XXXXXXXXX";
        end if; 
    end process;


    left_V_we0_assign_proc : process(ap_CS_fsm_state4, or_ln34_fu_617_p2)
    begin
        if ((((or_ln34_fu_617_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (or_ln34_fu_617_p2 = ap_const_lv1_0)))) then 
            left_V_we0 <= ap_const_logic_1;
        else 
            left_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln1_fu_547_p4 <= ret_V_fu_541_p2(9 downto 1);
    lshr_ln_fu_521_p4 <= t_V_2_reg_286(8 downto 1);
    or_ln34_fu_617_p2 <= (icmp_ln879_fu_611_p2 or and_ln34_fu_605_p2);
    or_ln52_fu_669_p2 <= (icmp_ln879_3_fu_663_p2 or and_ln52_fu_657_p2);

    parent_V_address0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state6, zext_ln544_fu_563_p1, zext_ln544_4_fu_693_p1, zext_ln544_3_fu_729_p1, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            parent_V_address0 <= zext_ln544_3_fu_729_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            parent_V_address0 <= zext_ln544_4_fu_693_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            parent_V_address0 <= zext_ln544_fu_563_p1(8 - 1 downto 0);
        else 
            parent_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    parent_V_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            parent_V_ce0 <= ap_const_logic_1;
        else 
            parent_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    parent_V_d0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state6, op_assign_reg_310, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            parent_V_d0 <= ap_const_lv9_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            parent_V_d0 <= op_assign_reg_310;
        else 
            parent_V_d0 <= "XXXXXXXXX";
        end if; 
    end process;


    parent_V_we0_assign_proc : process(ap_CS_fsm_state4, or_ln34_fu_617_p2, or_ln52_fu_669_p2, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (or_ln34_fu_617_p2 = ap_const_lv1_0)))) then 
            parent_V_we0 <= ap_const_logic_1;
        else 
            parent_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_fu_541_p2 <= std_logic_vector(unsigned(ap_const_lv10_1) + unsigned(zext_ln215_fu_537_p1));
    right_V_address0 <= right_V_addr_reg_835;

    right_V_ce0_assign_proc : process(or_ln52_fu_669_p2, ap_CS_fsm_state6)
    begin
        if ((((or_ln52_fu_669_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0)))) then 
            right_V_ce0 <= ap_const_logic_1;
        else 
            right_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    right_V_d0_assign_proc : process(or_ln52_fu_669_p2, ap_CS_fsm_state6, s_0_1_i_i_reg_357)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
            if ((or_ln52_fu_669_p2 = ap_const_lv1_1)) then 
                right_V_d0 <= s_0_1_i_i_reg_357;
            elsif ((or_ln52_fu_669_p2 = ap_const_lv1_0)) then 
                right_V_d0 <= ap_const_lv9_1FF;
            else 
                right_V_d0 <= "XXXXXXXXX";
            end if;
        else 
            right_V_d0 <= "XXXXXXXXX";
        end if; 
    end process;


    right_V_we0_assign_proc : process(or_ln52_fu_669_p2, ap_CS_fsm_state6)
    begin
        if ((((or_ln52_fu_669_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (or_ln52_fu_669_p2 = ap_const_lv1_0)))) then 
            right_V_we0 <= ap_const_logic_1;
        else 
            right_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tree_count_V_1_fu_698_p2 <= std_logic_vector(unsigned(t_V_4_reg_370) + unsigned(ap_const_lv9_1));
    tree_count_V_fu_628_p2 <= std_logic_vector(unsigned(t_V_2_reg_286) + unsigned(ap_const_lv9_1));
    trunc_ln31_fu_568_p1 <= t_V_2_reg_286(1 - 1 downto 0);
    trunc_ln321_1_fu_683_p1 <= op_assign_reg_310(1 - 1 downto 0);
    trunc_ln321_fu_712_p1 <= op_assign_reg_310(1 - 1 downto 0);
    xor_ln34_fu_599_p2 <= (icmp_ln34_1_fu_593_p2 xor ap_const_lv1_1);
    xor_ln52_fu_651_p2 <= (icmp_ln52_1_fu_645_p2 xor ap_const_lv1_1);
    zext_ln215_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_2_reg_286),10));
    zext_ln243_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op_assign_reg_310),10));
    zext_ln31_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_521_p4),64));
    zext_ln321_1_fu_687_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_487_p4),64));
    zext_ln321_fu_716_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_487_p4),64));
    zext_ln32_fu_557_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_547_p4),64));
    zext_ln36_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op_assign_reg_310),64));
    zext_ln544_3_fu_729_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_2_reg_286),64));
    zext_ln544_4_fu_693_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_4_reg_370),64));
    zext_ln544_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_2_reg_286),64));
end behav;
