// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "compute_bit_length.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic compute_bit_length::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic compute_bit_length::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> compute_bit_length::ap_ST_fsm_state1 = "1";
const sc_lv<9> compute_bit_length::ap_ST_fsm_state2 = "10";
const sc_lv<9> compute_bit_length::ap_ST_fsm_state3 = "100";
const sc_lv<9> compute_bit_length::ap_ST_fsm_state4 = "1000";
const sc_lv<9> compute_bit_length::ap_ST_fsm_state5 = "10000";
const sc_lv<9> compute_bit_length::ap_ST_fsm_state6 = "100000";
const sc_lv<9> compute_bit_length::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> compute_bit_length::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> compute_bit_length::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> compute_bit_length::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> compute_bit_length::ap_const_lv32_1 = "1";
const sc_lv<32> compute_bit_length::ap_const_lv32_2 = "10";
const sc_lv<32> compute_bit_length::ap_const_lv32_3 = "11";
const sc_lv<32> compute_bit_length::ap_const_lv32_4 = "100";
const sc_lv<32> compute_bit_length::ap_const_lv32_5 = "101";
const sc_lv<1> compute_bit_length::ap_const_lv1_0 = "0";
const sc_lv<32> compute_bit_length::ap_const_lv32_6 = "110";
const sc_lv<32> compute_bit_length::ap_const_lv32_7 = "111";
const sc_lv<7> compute_bit_length::ap_const_lv7_0 = "0000000";
const sc_lv<2> compute_bit_length::ap_const_lv2_1 = "1";
const sc_lv<1> compute_bit_length::ap_const_lv1_1 = "1";
const sc_lv<2> compute_bit_length::ap_const_lv2_2 = "10";
const sc_lv<9> compute_bit_length::ap_const_lv9_0 = "000000000";
const sc_lv<6> compute_bit_length::ap_const_lv6_1 = "1";
const sc_lv<7> compute_bit_length::ap_const_lv7_40 = "1000000";
const sc_lv<7> compute_bit_length::ap_const_lv7_1 = "1";
const sc_lv<10> compute_bit_length::ap_const_lv10_3FE = "1111111110";
const sc_lv<10> compute_bit_length::ap_const_lv10_3FD = "1111111101";
const sc_lv<10> compute_bit_length::ap_const_lv10_3FC = "1111111100";
const sc_lv<32> compute_bit_length::ap_const_lv32_1F = "11111";
const sc_lv<9> compute_bit_length::ap_const_lv9_1FF = "111111111";
const sc_lv<32> compute_bit_length::ap_const_lv32_FFFFFFFE = "11111111111111111111111111111110";
const sc_lv<32> compute_bit_length::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> compute_bit_length::ap_const_lv32_8 = "1000";
const bool compute_bit_length::ap_const_boolean_1 = true;

compute_bit_length::compute_bit_length(sc_module_name name) : sc_module(name), mVcdFile(0) {
    child_depth_V_U = new compute_bit_lengtjbC("child_depth_V_U");
    child_depth_V_U->clk(ap_clk);
    child_depth_V_U->reset(ap_rst);
    child_depth_V_U->address0(child_depth_V_address0);
    child_depth_V_U->ce0(child_depth_V_ce0);
    child_depth_V_U->we0(child_depth_V_we0);
    child_depth_V_U->d0(ap_var_for_const0);
    child_depth_V_U->q0(child_depth_V_q0);
    child_depth_V_U->address1(child_depth_V_address1);
    child_depth_V_U->ce1(child_depth_V_ce1);
    child_depth_V_U->we1(child_depth_V_we1);
    child_depth_V_U->d1(length_V_fu_460_p2);
    child_depth_V_U->q1(child_depth_V_q1);
    internal_length_hist_U = new compute_bit_lengtkbM("internal_length_hist_U");
    internal_length_hist_U->clk(ap_clk);
    internal_length_hist_U->reset(ap_rst);
    internal_length_hist_U->address0(internal_length_hist_address0);
    internal_length_hist_U->ce0(internal_length_hist_ce0);
    internal_length_hist_U->we0(internal_length_hist_we0);
    internal_length_hist_U->d0(internal_length_hist_d0);
    internal_length_hist_U->q0(internal_length_hist_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln23_fu_405_p2);
    sensitive << ( zext_ln13_reg_543 );

    SC_METHOD(thread_add_ln26_fu_427_p2);
    sensitive << ( zext_ln13_reg_543 );

    SC_METHOD(thread_add_ln61_fu_507_p2);
    sensitive << ( op2_assign_reg_360 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( extLd_loc_empty_n );

    SC_METHOD(thread_ap_condition_239);
    sensitive << ( tmp_fu_452_p3 );
    sensitive << ( icmp_ln883_fu_472_p2 );
    sensitive << ( icmp_ln883_1_fu_478_p2 );

    SC_METHOD(thread_ap_condition_242);
    sensitive << ( tmp_fu_452_p3 );
    sensitive << ( icmp_ln883_fu_472_p2 );
    sensitive << ( icmp_ln883_1_fu_478_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_child_depth_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( sext_ln23_fu_410_p1 );
    sensitive << ( zext_ln544_fu_439_p1 );
    sensitive << ( zext_ln544_8_fu_532_p1 );

    SC_METHOD(thread_child_depth_V_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln544_5_fu_444_p1 );
    sensitive << ( zext_ln40_fu_467_p1 );

    SC_METHOD(thread_child_depth_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_child_depth_V_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_child_depth_V_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_child_depth_V_we1);
    sensitive << ( tmp_fu_452_p3 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_child_depth_curr_V_1_fu_499_p3);
    sensitive << ( p_097_0_i_i_reg_293 );
    sensitive << ( length_V_fu_460_p2 );
    sensitive << ( icmp_ln879_fu_493_p2 );

    SC_METHOD(thread_count_V_1_fu_524_p2);
    sensitive << ( internal_length_hist_q0 );
    sensitive << ( zext_ln544_6_fu_520_p1 );

    SC_METHOD(thread_extLd_loc_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( extLd_loc_empty_n );

    SC_METHOD(thread_extLd_loc_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( extLd_loc_empty_n );

    SC_METHOD(thread_i_5_fu_393_p2);
    sensitive << ( i_0_i_i_reg_282 );

    SC_METHOD(thread_i_6_fu_537_p2);
    sensitive << ( op2_assign_reg_360 );

    SC_METHOD(thread_i_fu_415_p2);
    sensitive << ( zext_ln13_reg_543 );

    SC_METHOD(thread_icmp_ln17_fu_387_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_i_i_reg_282 );

    SC_METHOD(thread_icmp_ln879_fu_493_p2);
    sensitive << ( tmp_fu_452_p3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( op2_assign_reg_360 );
    sensitive << ( zext_ln879_fu_489_p1 );

    SC_METHOD(thread_icmp_ln883_1_fu_478_p2);
    sensitive << ( tmp_fu_452_p3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( p_07_0_i_i_reg_331 );

    SC_METHOD(thread_icmp_ln883_fu_472_p2);
    sensitive << ( tmp_fu_452_p3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( p_09_0_i_i_reg_311 );

    SC_METHOD(thread_internal_length_hist_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln544_7_fu_484_p1 );
    sensitive << ( internal_length_hist_2_reg_660 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln19_fu_399_p1 );

    SC_METHOD(thread_internal_length_hist_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_internal_length_hist_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( count_V_1_fu_524_p2 );

    SC_METHOD(thread_internal_length_hist_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_reg_643 );
    sensitive << ( icmp_ln883_reg_647 );
    sensitive << ( icmp_ln883_1_reg_651 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln17_fu_387_p2 );

    SC_METHOD(thread_left_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln25_fu_420_p1 );
    sensitive << ( sext_ln61_fu_513_p1 );

    SC_METHOD(thread_left_V_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln26_fu_432_p1 );

    SC_METHOD(thread_left_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_left_V_ce1);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_length_V_fu_460_p2);
    sensitive << ( p_0106_0_i_i_reg_351 );

    SC_METHOD(thread_length_histogram_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln544_7_reg_655 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln19_fu_399_p1 );

    SC_METHOD(thread_length_histogram_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_length_histogram_V_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( count_V_1_fu_524_p2 );

    SC_METHOD(thread_length_histogram_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_reg_643 );
    sensitive << ( icmp_ln883_reg_647 );
    sensitive << ( icmp_ln883_1_reg_651 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln17_fu_387_p2 );

    SC_METHOD(thread_parent_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln25_fu_420_p1 );
    sensitive << ( sext_ln61_fu_513_p1 );

    SC_METHOD(thread_parent_V_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln26_fu_432_p1 );

    SC_METHOD(thread_parent_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_parent_V_ce1);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_right_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln25_fu_420_p1 );
    sensitive << ( sext_ln61_fu_513_p1 );

    SC_METHOD(thread_right_V_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln26_fu_432_p1 );

    SC_METHOD(thread_right_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_right_V_ce1);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_sext_ln23_fu_410_p1);
    sensitive << ( add_ln23_fu_405_p2 );

    SC_METHOD(thread_sext_ln25_1_fu_449_p1);
    sensitive << ( i_reg_558 );

    SC_METHOD(thread_sext_ln25_fu_420_p1);
    sensitive << ( i_fu_415_p2 );

    SC_METHOD(thread_sext_ln26_fu_432_p1);
    sensitive << ( add_ln26_fu_427_p2 );

    SC_METHOD(thread_sext_ln61_fu_513_p1);
    sensitive << ( add_ln61_fu_507_p2 );

    SC_METHOD(thread_tmp_fu_452_p3);
    sensitive << ( op2_assign_reg_360 );

    SC_METHOD(thread_zext_ln13_fu_383_p1);
    sensitive << ( extLd_loc_dout );

    SC_METHOD(thread_zext_ln19_fu_399_p1);
    sensitive << ( i_0_i_i_reg_282 );

    SC_METHOD(thread_zext_ln40_fu_467_p1);
    sensitive << ( op2_assign_reg_360 );

    SC_METHOD(thread_zext_ln544_5_fu_444_p1);
    sensitive << ( parent_V_q1 );

    SC_METHOD(thread_zext_ln544_6_fu_520_p1);
    sensitive << ( phi_ln700_i_i_reg_370 );

    SC_METHOD(thread_zext_ln544_7_fu_484_p1);
    sensitive << ( length_V_fu_460_p2 );

    SC_METHOD(thread_zext_ln544_8_fu_532_p1);
    sensitive << ( parent_V_q0 );

    SC_METHOD(thread_zext_ln544_fu_439_p1);
    sensitive << ( parent_V_q0 );

    SC_METHOD(thread_zext_ln879_fu_489_p1);
    sensitive << ( p_0104_0_i_i_reg_302 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( extLd_loc_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_452_p3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln17_fu_387_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "compute_bit_length_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, parent_V_address0, "(port)parent_V_address0");
    sc_trace(mVcdFile, parent_V_ce0, "(port)parent_V_ce0");
    sc_trace(mVcdFile, parent_V_q0, "(port)parent_V_q0");
    sc_trace(mVcdFile, parent_V_address1, "(port)parent_V_address1");
    sc_trace(mVcdFile, parent_V_ce1, "(port)parent_V_ce1");
    sc_trace(mVcdFile, parent_V_q1, "(port)parent_V_q1");
    sc_trace(mVcdFile, left_V_address0, "(port)left_V_address0");
    sc_trace(mVcdFile, left_V_ce0, "(port)left_V_ce0");
    sc_trace(mVcdFile, left_V_q0, "(port)left_V_q0");
    sc_trace(mVcdFile, left_V_address1, "(port)left_V_address1");
    sc_trace(mVcdFile, left_V_ce1, "(port)left_V_ce1");
    sc_trace(mVcdFile, left_V_q1, "(port)left_V_q1");
    sc_trace(mVcdFile, right_V_address0, "(port)right_V_address0");
    sc_trace(mVcdFile, right_V_ce0, "(port)right_V_ce0");
    sc_trace(mVcdFile, right_V_q0, "(port)right_V_q0");
    sc_trace(mVcdFile, right_V_address1, "(port)right_V_address1");
    sc_trace(mVcdFile, right_V_ce1, "(port)right_V_ce1");
    sc_trace(mVcdFile, right_V_q1, "(port)right_V_q1");
    sc_trace(mVcdFile, extLd_loc_dout, "(port)extLd_loc_dout");
    sc_trace(mVcdFile, extLd_loc_empty_n, "(port)extLd_loc_empty_n");
    sc_trace(mVcdFile, extLd_loc_read, "(port)extLd_loc_read");
    sc_trace(mVcdFile, length_histogram_V_address0, "(port)length_histogram_V_address0");
    sc_trace(mVcdFile, length_histogram_V_ce0, "(port)length_histogram_V_ce0");
    sc_trace(mVcdFile, length_histogram_V_we0, "(port)length_histogram_V_we0");
    sc_trace(mVcdFile, length_histogram_V_d0, "(port)length_histogram_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, extLd_loc_blk_n, "extLd_loc_blk_n");
    sc_trace(mVcdFile, zext_ln13_fu_383_p1, "zext_ln13_fu_383_p1");
    sc_trace(mVcdFile, zext_ln13_reg_543, "zext_ln13_reg_543");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, i_5_fu_393_p2, "i_5_fu_393_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_415_p2, "i_fu_415_p2");
    sc_trace(mVcdFile, i_reg_558, "i_reg_558");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, parent_next_V_reg_593, "parent_next_V_reg_593");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, left_curr_V_reg_598, "left_curr_V_reg_598");
    sc_trace(mVcdFile, left_next_V_reg_603, "left_next_V_reg_603");
    sc_trace(mVcdFile, right_curr_V_reg_608, "right_curr_V_reg_608");
    sc_trace(mVcdFile, right_next_V_reg_613, "right_next_V_reg_613");
    sc_trace(mVcdFile, sext_ln25_1_fu_449_p1, "sext_ln25_1_fu_449_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, child_depth_V_q0, "child_depth_V_q0");
    sc_trace(mVcdFile, child_depth_V_q1, "child_depth_V_q1");
    sc_trace(mVcdFile, tmp_fu_452_p3, "tmp_fu_452_p3");
    sc_trace(mVcdFile, tmp_reg_643, "tmp_reg_643");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln883_fu_472_p2, "icmp_ln883_fu_472_p2");
    sc_trace(mVcdFile, icmp_ln883_reg_647, "icmp_ln883_reg_647");
    sc_trace(mVcdFile, icmp_ln883_1_fu_478_p2, "icmp_ln883_1_fu_478_p2");
    sc_trace(mVcdFile, icmp_ln883_1_reg_651, "icmp_ln883_1_reg_651");
    sc_trace(mVcdFile, zext_ln544_7_fu_484_p1, "zext_ln544_7_fu_484_p1");
    sc_trace(mVcdFile, zext_ln544_7_reg_655, "zext_ln544_7_reg_655");
    sc_trace(mVcdFile, internal_length_hist_2_reg_660, "internal_length_hist_2_reg_660");
    sc_trace(mVcdFile, child_depth_curr_V_1_fu_499_p3, "child_depth_curr_V_1_fu_499_p3");
    sc_trace(mVcdFile, child_depth_curr_V_1_reg_665, "child_depth_curr_V_1_reg_665");
    sc_trace(mVcdFile, parent_next_V_1_reg_685, "parent_next_V_1_reg_685");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, left_next_V_1_reg_690, "left_next_V_1_reg_690");
    sc_trace(mVcdFile, right_next_V_1_reg_695, "right_next_V_1_reg_695");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, i_6_fu_537_p2, "i_6_fu_537_p2");
    sc_trace(mVcdFile, child_depth_V_address0, "child_depth_V_address0");
    sc_trace(mVcdFile, child_depth_V_ce0, "child_depth_V_ce0");
    sc_trace(mVcdFile, child_depth_V_we0, "child_depth_V_we0");
    sc_trace(mVcdFile, child_depth_V_address1, "child_depth_V_address1");
    sc_trace(mVcdFile, child_depth_V_ce1, "child_depth_V_ce1");
    sc_trace(mVcdFile, child_depth_V_we1, "child_depth_V_we1");
    sc_trace(mVcdFile, internal_length_hist_address0, "internal_length_hist_address0");
    sc_trace(mVcdFile, internal_length_hist_ce0, "internal_length_hist_ce0");
    sc_trace(mVcdFile, internal_length_hist_we0, "internal_length_hist_we0");
    sc_trace(mVcdFile, internal_length_hist_d0, "internal_length_hist_d0");
    sc_trace(mVcdFile, internal_length_hist_q0, "internal_length_hist_q0");
    sc_trace(mVcdFile, i_0_i_i_reg_282, "i_0_i_i_reg_282");
    sc_trace(mVcdFile, icmp_ln17_fu_387_p2, "icmp_ln17_fu_387_p2");
    sc_trace(mVcdFile, p_097_0_i_i_reg_293, "p_097_0_i_i_reg_293");
    sc_trace(mVcdFile, p_0104_0_i_i_reg_302, "p_0104_0_i_i_reg_302");
    sc_trace(mVcdFile, p_09_0_i_i_reg_311, "p_09_0_i_i_reg_311");
    sc_trace(mVcdFile, left_curr_V_1_reg_320, "left_curr_V_1_reg_320");
    sc_trace(mVcdFile, p_07_0_i_i_reg_331, "p_07_0_i_i_reg_331");
    sc_trace(mVcdFile, right_curr_V_1_reg_340, "right_curr_V_1_reg_340");
    sc_trace(mVcdFile, p_0106_0_i_i_reg_351, "p_0106_0_i_i_reg_351");
    sc_trace(mVcdFile, op2_assign_reg_360, "op2_assign_reg_360");
    sc_trace(mVcdFile, phi_ln700_i_i_reg_370, "phi_ln700_i_i_reg_370");
    sc_trace(mVcdFile, zext_ln19_fu_399_p1, "zext_ln19_fu_399_p1");
    sc_trace(mVcdFile, sext_ln23_fu_410_p1, "sext_ln23_fu_410_p1");
    sc_trace(mVcdFile, sext_ln25_fu_420_p1, "sext_ln25_fu_420_p1");
    sc_trace(mVcdFile, sext_ln26_fu_432_p1, "sext_ln26_fu_432_p1");
    sc_trace(mVcdFile, zext_ln544_fu_439_p1, "zext_ln544_fu_439_p1");
    sc_trace(mVcdFile, zext_ln544_5_fu_444_p1, "zext_ln544_5_fu_444_p1");
    sc_trace(mVcdFile, zext_ln40_fu_467_p1, "zext_ln40_fu_467_p1");
    sc_trace(mVcdFile, sext_ln61_fu_513_p1, "sext_ln61_fu_513_p1");
    sc_trace(mVcdFile, zext_ln544_8_fu_532_p1, "zext_ln544_8_fu_532_p1");
    sc_trace(mVcdFile, count_V_1_fu_524_p2, "count_V_1_fu_524_p2");
    sc_trace(mVcdFile, length_V_fu_460_p2, "length_V_fu_460_p2");
    sc_trace(mVcdFile, add_ln23_fu_405_p2, "add_ln23_fu_405_p2");
    sc_trace(mVcdFile, add_ln26_fu_427_p2, "add_ln26_fu_427_p2");
    sc_trace(mVcdFile, zext_ln879_fu_489_p1, "zext_ln879_fu_489_p1");
    sc_trace(mVcdFile, icmp_ln879_fu_493_p2, "icmp_ln879_fu_493_p2");
    sc_trace(mVcdFile, add_ln61_fu_507_p2, "add_ln61_fu_507_p2");
    sc_trace(mVcdFile, zext_ln544_6_fu_520_p1, "zext_ln544_6_fu_520_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_239, "ap_condition_239");
    sc_trace(mVcdFile, ap_condition_242, "ap_condition_242");
#endif

    }
}

compute_bit_length::~compute_bit_length() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete child_depth_V_U;
    delete internal_length_hist_U;
}

void compute_bit_length::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv6_1;
}

void compute_bit_length::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read())))) {
        i_0_i_i_reg_282 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_fu_387_p2.read()))) {
        i_0_i_i_reg_282 = i_5_fu_393_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        left_curr_V_1_reg_320 = left_next_V_1_reg_690.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        left_curr_V_1_reg_320 = left_next_V_reg_603.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        op2_assign_reg_360 = i_6_fu_537_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        op2_assign_reg_360 = sext_ln25_1_fu_449_p1.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        p_0104_0_i_i_reg_302 = parent_next_V_1_reg_685.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_0104_0_i_i_reg_302 = parent_next_V_reg_593.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        p_0106_0_i_i_reg_351 = child_depth_curr_V_1_reg_665.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_0106_0_i_i_reg_351 = child_depth_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        p_07_0_i_i_reg_331 = right_curr_V_1_reg_340.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_07_0_i_i_reg_331 = right_curr_V_reg_608.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        p_097_0_i_i_reg_293 = child_depth_V_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_097_0_i_i_reg_293 = child_depth_V_q1.read();
    }
    if ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        p_09_0_i_i_reg_311 = left_curr_V_1_reg_320.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_09_0_i_i_reg_311 = left_curr_V_reg_598.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        if (esl_seteq<1,1,1>(ap_condition_242.read(), ap_const_boolean_1)) {
            phi_ln700_i_i_reg_370 = ap_const_lv2_2;
        } else if (esl_seteq<1,1,1>(ap_condition_239.read(), ap_const_boolean_1)) {
            phi_ln700_i_i_reg_370 = ap_const_lv2_1;
        }
    }
    if ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        right_curr_V_1_reg_340 = right_next_V_1_reg_695.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        right_curr_V_1_reg_340 = right_next_V_reg_613.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(tmp_fu_452_p3.read(), ap_const_lv1_0))) {
        child_depth_curr_V_1_reg_665 = child_depth_curr_V_1_fu_499_p3.read();
        icmp_ln883_1_reg_651 = icmp_ln883_1_fu_478_p2.read();
        icmp_ln883_reg_647 = icmp_ln883_fu_472_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_558 = i_fu_415_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && ((esl_seteq<1,1,1>(tmp_fu_452_p3.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln883_1_fu_478_p2.read())) || 
  (esl_seteq<1,1,1>(tmp_fu_452_p3.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(icmp_ln883_fu_472_p2.read(), ap_const_lv1_0))))) {
        internal_length_hist_2_reg_660 =  (sc_lv<6>) (zext_ln544_7_fu_484_p1.read());
        zext_ln544_7_reg_655 = zext_ln544_7_fu_484_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        left_curr_V_reg_598 = left_V_q0.read();
        left_next_V_reg_603 = left_V_q1.read();
        parent_next_V_reg_593 = parent_V_q1.read();
        right_curr_V_reg_608 = right_V_q0.read();
        right_next_V_reg_613 = right_V_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0))) {
        left_next_V_1_reg_690 = left_V_q0.read();
        parent_next_V_1_reg_685 = parent_V_q0.read();
        right_next_V_1_reg_695 = right_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_reg_643 = op2_assign_reg_360.read().range(31, 31);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read())))) {
        zext_ln13_reg_543 = zext_ln13_fu_383_p1.read();
    }
}

void compute_bit_length::thread_add_ln23_fu_405_p2() {
    add_ln23_fu_405_p2 = (!zext_ln13_reg_543.read().is_01() || !ap_const_lv10_3FE.is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln13_reg_543.read()) + sc_bigint<10>(ap_const_lv10_3FE));
}

void compute_bit_length::thread_add_ln26_fu_427_p2() {
    add_ln26_fu_427_p2 = (!zext_ln13_reg_543.read().is_01() || !ap_const_lv10_3FC.is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln13_reg_543.read()) + sc_bigint<10>(ap_const_lv10_3FC));
}

void compute_bit_length::thread_add_ln61_fu_507_p2() {
    add_ln61_fu_507_p2 = (!op2_assign_reg_360.read().is_01() || !ap_const_lv32_FFFFFFFE.is_01())? sc_lv<32>(): (sc_biguint<32>(op2_assign_reg_360.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFE));
}

void compute_bit_length::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void compute_bit_length::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void compute_bit_length::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void compute_bit_length::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void compute_bit_length::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void compute_bit_length::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void compute_bit_length::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void compute_bit_length::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void compute_bit_length::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void compute_bit_length::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read()));
}

void compute_bit_length::thread_ap_condition_239() {
    ap_condition_239 = ((esl_seteq<1,1,1>(tmp_fu_452_p3.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln883_1_fu_478_p2.read()) && 
  esl_seteq<1,1,1>(icmp_ln883_fu_472_p2.read(), ap_const_lv1_1)) || (esl_seteq<1,1,1>(tmp_fu_452_p3.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(icmp_ln883_fu_472_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(icmp_ln883_1_fu_478_p2.read(), ap_const_lv1_1)));
}

void compute_bit_length::thread_ap_condition_242() {
    ap_condition_242 = (esl_seteq<1,1,1>(tmp_fu_452_p3.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln883_1_fu_478_p2.read()) && esl_seteq<1,1,1>(icmp_ln883_fu_472_p2.read(), ap_const_lv1_0));
}

void compute_bit_length::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void compute_bit_length::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void compute_bit_length::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void compute_bit_length::thread_child_depth_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        child_depth_V_address0 =  (sc_lv<8>) (zext_ln544_8_fu_532_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        child_depth_V_address0 =  (sc_lv<8>) (zext_ln544_fu_439_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        child_depth_V_address0 =  (sc_lv<8>) (sext_ln23_fu_410_p1.read());
    } else {
        child_depth_V_address0 = "XXXXXXXX";
    }
}

void compute_bit_length::thread_child_depth_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        child_depth_V_address1 =  (sc_lv<8>) (zext_ln40_fu_467_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        child_depth_V_address1 =  (sc_lv<8>) (zext_ln544_5_fu_444_p1.read());
    } else {
        child_depth_V_address1 = "XXXXXXXX";
    }
}

void compute_bit_length::thread_child_depth_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        child_depth_V_ce0 = ap_const_logic_1;
    } else {
        child_depth_V_ce0 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_child_depth_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        child_depth_V_ce1 = ap_const_logic_1;
    } else {
        child_depth_V_ce1 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_child_depth_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        child_depth_V_we0 = ap_const_logic_1;
    } else {
        child_depth_V_we0 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_child_depth_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(tmp_fu_452_p3.read(), ap_const_lv1_0))) {
        child_depth_V_we1 = ap_const_logic_1;
    } else {
        child_depth_V_we1 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_child_depth_curr_V_1_fu_499_p3() {
    child_depth_curr_V_1_fu_499_p3 = (!icmp_ln879_fu_493_p2.read()[0].is_01())? sc_lv<6>(): ((icmp_ln879_fu_493_p2.read()[0].to_bool())? length_V_fu_460_p2.read(): p_097_0_i_i_reg_293.read());
}

void compute_bit_length::thread_count_V_1_fu_524_p2() {
    count_V_1_fu_524_p2 = (!internal_length_hist_q0.read().is_01() || !zext_ln544_6_fu_520_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(internal_length_hist_q0.read()) + sc_biguint<9>(zext_ln544_6_fu_520_p1.read()));
}

void compute_bit_length::thread_extLd_loc_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        extLd_loc_blk_n = extLd_loc_empty_n.read();
    } else {
        extLd_loc_blk_n = ap_const_logic_1;
    }
}

void compute_bit_length::thread_extLd_loc_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read())))) {
        extLd_loc_read = ap_const_logic_1;
    } else {
        extLd_loc_read = ap_const_logic_0;
    }
}

void compute_bit_length::thread_i_5_fu_393_p2() {
    i_5_fu_393_p2 = (!i_0_i_i_reg_282.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_0_i_i_reg_282.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void compute_bit_length::thread_i_6_fu_537_p2() {
    i_6_fu_537_p2 = (!op2_assign_reg_360.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(op2_assign_reg_360.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void compute_bit_length::thread_i_fu_415_p2() {
    i_fu_415_p2 = (!zext_ln13_reg_543.read().is_01() || !ap_const_lv10_3FD.is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln13_reg_543.read()) + sc_bigint<10>(ap_const_lv10_3FD));
}

void compute_bit_length::thread_icmp_ln17_fu_387_p2() {
    icmp_ln17_fu_387_p2 = (!i_0_i_i_reg_282.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_i_reg_282.read() == ap_const_lv7_40);
}

void compute_bit_length::thread_icmp_ln879_fu_493_p2() {
    icmp_ln879_fu_493_p2 = (!zext_ln879_fu_489_p1.read().is_01() || !op2_assign_reg_360.read().is_01())? sc_lv<1>(): sc_lv<1>(zext_ln879_fu_489_p1.read() == op2_assign_reg_360.read());
}

void compute_bit_length::thread_icmp_ln883_1_fu_478_p2() {
    icmp_ln883_1_fu_478_p2 = (!p_07_0_i_i_reg_331.read().is_01() || !ap_const_lv9_1FF.is_01())? sc_lv<1>(): sc_lv<1>(p_07_0_i_i_reg_331.read() == ap_const_lv9_1FF);
}

void compute_bit_length::thread_icmp_ln883_fu_472_p2() {
    icmp_ln883_fu_472_p2 = (!p_09_0_i_i_reg_311.read().is_01() || !ap_const_lv9_1FF.is_01())? sc_lv<1>(): sc_lv<1>(p_09_0_i_i_reg_311.read() == ap_const_lv9_1FF);
}

void compute_bit_length::thread_internal_length_hist_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        internal_length_hist_address0 = internal_length_hist_2_reg_660.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        internal_length_hist_address0 =  (sc_lv<6>) (zext_ln544_7_fu_484_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        internal_length_hist_address0 =  (sc_lv<6>) (zext_ln19_fu_399_p1.read());
    } else {
        internal_length_hist_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void compute_bit_length::thread_internal_length_hist_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        internal_length_hist_ce0 = ap_const_logic_1;
    } else {
        internal_length_hist_ce0 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_internal_length_hist_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        internal_length_hist_d0 = count_V_1_fu_524_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        internal_length_hist_d0 = ap_const_lv9_0;
    } else {
        internal_length_hist_d0 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void compute_bit_length::thread_internal_length_hist_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_fu_387_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln883_1_reg_651.read())) || 
           (esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(icmp_ln883_reg_647.read(), ap_const_lv1_0)))))) {
        internal_length_hist_we0 = ap_const_logic_1;
    } else {
        internal_length_hist_we0 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_left_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        left_V_address0 =  (sc_lv<8>) (sext_ln61_fu_513_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        left_V_address0 =  (sc_lv<8>) (sext_ln25_fu_420_p1.read());
    } else {
        left_V_address0 = "XXXXXXXX";
    }
}

void compute_bit_length::thread_left_V_address1() {
    left_V_address1 =  (sc_lv<8>) (sext_ln26_fu_432_p1.read());
}

void compute_bit_length::thread_left_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        left_V_ce0 = ap_const_logic_1;
    } else {
        left_V_ce0 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_left_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        left_V_ce1 = ap_const_logic_1;
    } else {
        left_V_ce1 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_length_V_fu_460_p2() {
    length_V_fu_460_p2 = (!p_0106_0_i_i_reg_351.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(p_0106_0_i_i_reg_351.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void compute_bit_length::thread_length_histogram_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        length_histogram_V_address0 =  (sc_lv<6>) (zext_ln544_7_reg_655.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        length_histogram_V_address0 =  (sc_lv<6>) (zext_ln19_fu_399_p1.read());
    } else {
        length_histogram_V_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void compute_bit_length::thread_length_histogram_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        length_histogram_V_ce0 = ap_const_logic_1;
    } else {
        length_histogram_V_ce0 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_length_histogram_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        length_histogram_V_d0 = count_V_1_fu_524_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        length_histogram_V_d0 = ap_const_lv9_0;
    } else {
        length_histogram_V_d0 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void compute_bit_length::thread_length_histogram_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_fu_387_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          ((esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln883_1_reg_651.read())) || 
           (esl_seteq<1,1,1>(tmp_reg_643.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(icmp_ln883_reg_647.read(), ap_const_lv1_0)))))) {
        length_histogram_V_we0 = ap_const_logic_1;
    } else {
        length_histogram_V_we0 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_parent_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        parent_V_address0 =  (sc_lv<8>) (sext_ln61_fu_513_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        parent_V_address0 =  (sc_lv<8>) (sext_ln25_fu_420_p1.read());
    } else {
        parent_V_address0 = "XXXXXXXX";
    }
}

void compute_bit_length::thread_parent_V_address1() {
    parent_V_address1 =  (sc_lv<8>) (sext_ln26_fu_432_p1.read());
}

void compute_bit_length::thread_parent_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        parent_V_ce0 = ap_const_logic_1;
    } else {
        parent_V_ce0 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_parent_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        parent_V_ce1 = ap_const_logic_1;
    } else {
        parent_V_ce1 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_right_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        right_V_address0 =  (sc_lv<8>) (sext_ln61_fu_513_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        right_V_address0 =  (sc_lv<8>) (sext_ln25_fu_420_p1.read());
    } else {
        right_V_address0 = "XXXXXXXX";
    }
}

void compute_bit_length::thread_right_V_address1() {
    right_V_address1 =  (sc_lv<8>) (sext_ln26_fu_432_p1.read());
}

void compute_bit_length::thread_right_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        right_V_ce0 = ap_const_logic_1;
    } else {
        right_V_ce0 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_right_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        right_V_ce1 = ap_const_logic_1;
    } else {
        right_V_ce1 = ap_const_logic_0;
    }
}

void compute_bit_length::thread_sext_ln23_fu_410_p1() {
    sext_ln23_fu_410_p1 = esl_sext<64,10>(add_ln23_fu_405_p2.read());
}

void compute_bit_length::thread_sext_ln25_1_fu_449_p1() {
    sext_ln25_1_fu_449_p1 = esl_sext<32,10>(i_reg_558.read());
}

void compute_bit_length::thread_sext_ln25_fu_420_p1() {
    sext_ln25_fu_420_p1 = esl_sext<64,10>(i_fu_415_p2.read());
}

void compute_bit_length::thread_sext_ln26_fu_432_p1() {
    sext_ln26_fu_432_p1 = esl_sext<64,10>(add_ln26_fu_427_p2.read());
}

void compute_bit_length::thread_sext_ln61_fu_513_p1() {
    sext_ln61_fu_513_p1 = esl_sext<64,32>(add_ln61_fu_507_p2.read());
}

void compute_bit_length::thread_tmp_fu_452_p3() {
    tmp_fu_452_p3 = op2_assign_reg_360.read().range(31, 31);
}

void compute_bit_length::thread_zext_ln13_fu_383_p1() {
    zext_ln13_fu_383_p1 = esl_zext<10,9>(extLd_loc_dout.read());
}

void compute_bit_length::thread_zext_ln19_fu_399_p1() {
    zext_ln19_fu_399_p1 = esl_zext<64,7>(i_0_i_i_reg_282.read());
}

void compute_bit_length::thread_zext_ln40_fu_467_p1() {
    zext_ln40_fu_467_p1 = esl_zext<64,32>(op2_assign_reg_360.read());
}

void compute_bit_length::thread_zext_ln544_5_fu_444_p1() {
    zext_ln544_5_fu_444_p1 = esl_zext<64,9>(parent_V_q1.read());
}

void compute_bit_length::thread_zext_ln544_6_fu_520_p1() {
    zext_ln544_6_fu_520_p1 = esl_zext<9,2>(phi_ln700_i_i_reg_370.read());
}

void compute_bit_length::thread_zext_ln544_7_fu_484_p1() {
    zext_ln544_7_fu_484_p1 = esl_zext<64,6>(length_V_fu_460_p2.read());
}

void compute_bit_length::thread_zext_ln544_8_fu_532_p1() {
    zext_ln544_8_fu_532_p1 = esl_zext<64,9>(parent_V_q0.read());
}

void compute_bit_length::thread_zext_ln544_fu_439_p1() {
    zext_ln544_fu_439_p1 = esl_zext<64,9>(parent_V_q0.read());
}

void compute_bit_length::thread_zext_ln879_fu_489_p1() {
    zext_ln879_fu_489_p1 = esl_zext<32,9>(p_0104_0_i_i_reg_302.read());
}

void compute_bit_length::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_fu_387_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(tmp_fu_452_p3.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

