// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "create_codeword.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic create_codeword::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic create_codeword::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> create_codeword::ap_ST_fsm_state1 = "1";
const sc_lv<9> create_codeword::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<9> create_codeword::ap_ST_fsm_state4 = "100";
const sc_lv<9> create_codeword::ap_ST_fsm_state5 = "1000";
const sc_lv<9> create_codeword::ap_ST_fsm_state6 = "10000";
const sc_lv<9> create_codeword::ap_ST_fsm_state7 = "100000";
const sc_lv<9> create_codeword::ap_ST_fsm_state8 = "1000000";
const sc_lv<9> create_codeword::ap_ST_fsm_state9 = "10000000";
const sc_lv<9> create_codeword::ap_ST_fsm_state10 = "100000000";
const sc_lv<32> create_codeword::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool create_codeword::ap_const_boolean_1 = true;
const sc_lv<32> create_codeword::ap_const_lv32_6 = "110";
const sc_lv<1> create_codeword::ap_const_lv1_0 = "0";
const sc_lv<32> create_codeword::ap_const_lv32_7 = "111";
const sc_lv<32> create_codeword::ap_const_lv32_1 = "1";
const bool create_codeword::ap_const_boolean_0 = false;
const sc_lv<32> create_codeword::ap_const_lv32_3 = "11";
const sc_lv<32> create_codeword::ap_const_lv32_4 = "100";
const sc_lv<1> create_codeword::ap_const_lv1_1 = "1";
const sc_lv<27> create_codeword::ap_const_lv27_0 = "000000000000000000000000000";
const sc_lv<5> create_codeword::ap_const_lv5_0 = "00000";
const sc_lv<9> create_codeword::ap_const_lv9_0 = "000000000";
const sc_lv<32> create_codeword::ap_const_lv32_2 = "10";
const sc_lv<32> create_codeword::ap_const_lv32_5 = "101";
const sc_lv<4> create_codeword::ap_const_lv4_F = "1111";
const sc_lv<5> create_codeword::ap_const_lv5_1B = "11011";
const sc_lv<5> create_codeword::ap_const_lv5_1 = "1";
const sc_lv<9> create_codeword::ap_const_lv9_100 = "100000000";
const sc_lv<9> create_codeword::ap_const_lv9_1 = "1";
const sc_lv<9> create_codeword::ap_const_lv9_FF = "11111111";
const sc_lv<32> create_codeword::ap_const_lv32_1A = "11010";
const sc_lv<6> create_codeword::ap_const_lv6_1B = "11011";
const sc_lv<3> create_codeword::ap_const_lv3_0 = "000";
const sc_lv<27> create_codeword::ap_const_lv27_1 = "1";
const sc_lv<32> create_codeword::ap_const_lv32_8 = "1000";

create_codeword::create_codeword(sc_module_name name) : sc_module(name), mVcdFile(0) {
    first_codeword_V_U = new create_codeword_flbW("first_codeword_V_U");
    first_codeword_V_U->clk(ap_clk);
    first_codeword_V_U->reset(ap_rst);
    first_codeword_V_U->address0(first_codeword_V_address0);
    first_codeword_V_U->ce0(first_codeword_V_ce0);
    first_codeword_V_U->we0(first_codeword_V_we0);
    first_codeword_V_U->d0(first_codeword_V_d0);
    first_codeword_V_U->q0(first_codeword_V_q0);
    regslice_both_encoding_V_data_V_U = new regslice_both<32>("regslice_both_encoding_V_data_V_U");
    regslice_both_encoding_V_data_V_U->ap_clk(ap_clk);
    regslice_both_encoding_V_data_V_U->ap_rst(ap_rst);
    regslice_both_encoding_V_data_V_U->data_in(tmp_data_V_fu_102);
    regslice_both_encoding_V_data_V_U->vld_in(encoding_TVALID_int);
    regslice_both_encoding_V_data_V_U->ack_in(encoding_TREADY_int);
    regslice_both_encoding_V_data_V_U->data_out(encoding_TDATA);
    regslice_both_encoding_V_data_V_U->vld_out(regslice_both_encoding_V_data_V_U_vld_out);
    regslice_both_encoding_V_data_V_U->ack_out(encoding_TREADY);
    regslice_both_encoding_V_data_V_U->apdone_blk(regslice_both_encoding_V_data_V_U_apdone_blk);
    regslice_both_encoding_V_keep_V_U = new regslice_both<4>("regslice_both_encoding_V_keep_V_U");
    regslice_both_encoding_V_keep_V_U->ap_clk(ap_clk);
    regslice_both_encoding_V_keep_V_U->ap_rst(ap_rst);
    regslice_both_encoding_V_keep_V_U->data_in(ap_var_for_const0);
    regslice_both_encoding_V_keep_V_U->vld_in(encoding_TVALID_int);
    regslice_both_encoding_V_keep_V_U->ack_in(regslice_both_encoding_V_keep_V_U_ack_in_dummy);
    regslice_both_encoding_V_keep_V_U->data_out(encoding_TKEEP);
    regslice_both_encoding_V_keep_V_U->vld_out(regslice_both_encoding_V_keep_V_U_vld_out);
    regslice_both_encoding_V_keep_V_U->ack_out(encoding_TREADY);
    regslice_both_encoding_V_keep_V_U->apdone_blk(regslice_both_encoding_V_keep_V_U_apdone_blk);
    regslice_both_encoding_V_strb_V_U = new regslice_both<4>("regslice_both_encoding_V_strb_V_U");
    regslice_both_encoding_V_strb_V_U->ap_clk(ap_clk);
    regslice_both_encoding_V_strb_V_U->ap_rst(ap_rst);
    regslice_both_encoding_V_strb_V_U->data_in(ap_var_for_const0);
    regslice_both_encoding_V_strb_V_U->vld_in(encoding_TVALID_int);
    regslice_both_encoding_V_strb_V_U->ack_in(regslice_both_encoding_V_strb_V_U_ack_in_dummy);
    regslice_both_encoding_V_strb_V_U->data_out(encoding_TSTRB);
    regslice_both_encoding_V_strb_V_U->vld_out(regslice_both_encoding_V_strb_V_U_vld_out);
    regslice_both_encoding_V_strb_V_U->ack_out(encoding_TREADY);
    regslice_both_encoding_V_strb_V_U->apdone_blk(regslice_both_encoding_V_strb_V_U_apdone_blk);
    regslice_both_encoding_V_user_V_U = new regslice_both<1>("regslice_both_encoding_V_user_V_U");
    regslice_both_encoding_V_user_V_U->ap_clk(ap_clk);
    regslice_both_encoding_V_user_V_U->ap_rst(ap_rst);
    regslice_both_encoding_V_user_V_U->data_in(result_user_V_reg_507);
    regslice_both_encoding_V_user_V_U->vld_in(encoding_TVALID_int);
    regslice_both_encoding_V_user_V_U->ack_in(regslice_both_encoding_V_user_V_U_ack_in_dummy);
    regslice_both_encoding_V_user_V_U->data_out(encoding_TUSER);
    regslice_both_encoding_V_user_V_U->vld_out(regslice_both_encoding_V_user_V_U_vld_out);
    regslice_both_encoding_V_user_V_U->ack_out(encoding_TREADY);
    regslice_both_encoding_V_user_V_U->apdone_blk(regslice_both_encoding_V_user_V_U_apdone_blk);
    regslice_both_encoding_V_last_V_U = new regslice_both<1>("regslice_both_encoding_V_last_V_U");
    regslice_both_encoding_V_last_V_U->ap_clk(ap_clk);
    regslice_both_encoding_V_last_V_U->ap_rst(ap_rst);
    regslice_both_encoding_V_last_V_U->data_in(result_last_V_reg_477);
    regslice_both_encoding_V_last_V_U->vld_in(encoding_TVALID_int);
    regslice_both_encoding_V_last_V_U->ack_in(regslice_both_encoding_V_last_V_U_ack_in_dummy);
    regslice_both_encoding_V_last_V_U->data_out(encoding_TLAST);
    regslice_both_encoding_V_last_V_U->vld_out(regslice_both_encoding_V_last_V_U_vld_out);
    regslice_both_encoding_V_last_V_U->ack_out(encoding_TREADY);
    regslice_both_encoding_V_last_V_U->apdone_blk(regslice_both_encoding_V_last_V_U_apdone_blk);
    regslice_both_encoding_V_id_V_U = new regslice_both<1>("regslice_both_encoding_V_id_V_U");
    regslice_both_encoding_V_id_V_U->ap_clk(ap_clk);
    regslice_both_encoding_V_id_V_U->ap_rst(ap_rst);
    regslice_both_encoding_V_id_V_U->data_in(result_id_V_reg_512);
    regslice_both_encoding_V_id_V_U->vld_in(encoding_TVALID_int);
    regslice_both_encoding_V_id_V_U->ack_in(regslice_both_encoding_V_id_V_U_ack_in_dummy);
    regslice_both_encoding_V_id_V_U->data_out(encoding_TID);
    regslice_both_encoding_V_id_V_U->vld_out(regslice_both_encoding_V_id_V_U_vld_out);
    regslice_both_encoding_V_id_V_U->ack_out(encoding_TREADY);
    regslice_both_encoding_V_id_V_U->apdone_blk(regslice_both_encoding_V_id_V_U_apdone_blk);
    regslice_both_encoding_V_dest_V_U = new regslice_both<1>("regslice_both_encoding_V_dest_V_U");
    regslice_both_encoding_V_dest_V_U->ap_clk(ap_clk);
    regslice_both_encoding_V_dest_V_U->ap_rst(ap_rst);
    regslice_both_encoding_V_dest_V_U->data_in(result_dest_V_reg_517);
    regslice_both_encoding_V_dest_V_U->vld_in(encoding_TVALID_int);
    regslice_both_encoding_V_dest_V_U->ack_in(regslice_both_encoding_V_dest_V_U_ack_in_dummy);
    regslice_both_encoding_V_dest_V_U->data_out(encoding_TDEST);
    regslice_both_encoding_V_dest_V_U->vld_out(regslice_both_encoding_V_dest_V_U_vld_out);
    regslice_both_encoding_V_dest_V_U->ack_out(encoding_TREADY);
    regslice_both_encoding_V_dest_V_U->apdone_blk(regslice_both_encoding_V_dest_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln1503_fu_277_p2);
    sensitive << ( trunc_ln1503_fu_273_p1 );
    sensitive << ( zext_ln1503_fu_269_p1 );

    SC_METHOD(thread_add_ln700_fu_412_p2);
    sensitive << ( first_codeword_V_q0 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state8_io);
    sensitive << ( icmp_ln26_reg_458 );
    sensitive << ( encoding_TREADY_int );

    SC_METHOD(thread_ap_block_state9_io);
    sensitive << ( icmp_ln26_reg_458 );
    sensitive << ( encoding_TREADY_int );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln18_fu_252_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( regslice_both_encoding_V_data_V_U_apdone_blk );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( regslice_both_encoding_V_data_V_U_apdone_blk );

    SC_METHOD(thread_codeword_length_histogram_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln21_fu_264_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_codeword_length_histogram_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_encoding_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln26_reg_458 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( encoding_TREADY_int );

    SC_METHOD(thread_encoding_TVALID);
    sensitive << ( regslice_both_encoding_V_data_V_U_vld_out );

    SC_METHOD(thread_encoding_TVALID_int);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln26_reg_458 );
    sensitive << ( ap_block_state8_io );

    SC_METHOD(thread_first_codeword_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln21_reg_437 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( first_codeword_V_add_1_reg_502 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln544_fu_323_p1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_first_codeword_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_first_codeword_V_d0);
    sensitive << ( p_0199_0_reg_217 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( add_ln700_fu_412_p2 );

    SC_METHOD(thread_first_codeword_V_we0);
    sensitive << ( icmp_ln26_reg_458 );
    sensitive << ( icmp_ln18_reg_428 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln883_reg_498 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_i_4_fu_297_p2);
    sensitive << ( i1_0_reg_241 );

    SC_METHOD(thread_i_fu_258_p2);
    sensitive << ( i_0_reg_230 );

    SC_METHOD(thread_icmp_ln18_fu_252_p2);
    sensitive << ( i_0_reg_230 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln26_fu_291_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_0_reg_241 );

    SC_METHOD(thread_icmp_ln883_fu_317_p2);
    sensitive << ( symbol_bits_V_q0 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_lshr_ln808_fu_379_p2);
    sensitive << ( p_Result_s_fu_328_p4 );
    sensitive << ( zext_ln808_fu_375_p1 );

    SC_METHOD(thread_p_Result_1_fu_347_p3);
    sensitive << ( ret_V_fu_341_p2 );

    SC_METHOD(thread_p_Result_s_fu_328_p4);
    sensitive << ( first_codeword_V_q0 );

    SC_METHOD(thread_r_V_fu_369_p2);
    sensitive << ( p_Result_s_fu_328_p4 );
    sensitive << ( zext_ln556_fu_365_p1 );

    SC_METHOD(thread_result_data_V_fu_408_p1);
    sensitive << ( tmp_2_fu_401_p3 );

    SC_METHOD(thread_result_last_V_fu_311_p2);
    sensitive << ( icmp_ln26_fu_291_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_0_reg_241 );

    SC_METHOD(thread_ret_V_fu_341_p2);
    sensitive << ( zext_ln215_fu_338_p1 );

    SC_METHOD(thread_select_ln796_fu_393_p3);
    sensitive << ( p_Result_1_fu_347_p3 );
    sensitive << ( trunc_ln796_fu_385_p1 );
    sensitive << ( trunc_ln796_1_fu_389_p1 );

    SC_METHOD(thread_stream_buffer_dest_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln28_fu_303_p1 );

    SC_METHOD(thread_stream_buffer_dest_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_stream_buffer_id_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln28_fu_303_p1 );

    SC_METHOD(thread_stream_buffer_id_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_stream_buffer_user_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln28_fu_303_p1 );

    SC_METHOD(thread_stream_buffer_user_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_sub_ln556_fu_359_p2);
    sensitive << ( trunc_ln790_fu_355_p1 );

    SC_METHOD(thread_symbol_bits_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln28_fu_303_p1 );

    SC_METHOD(thread_symbol_bits_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_temp_V_fu_283_p3);
    sensitive << ( add_ln1503_fu_277_p2 );

    SC_METHOD(thread_tmp_2_fu_401_p3);
    sensitive << ( length_V_reg_492 );
    sensitive << ( select_ln796_fu_393_p3 );

    SC_METHOD(thread_trunc_ln1503_fu_273_p1);
    sensitive << ( p_0199_0_reg_217 );

    SC_METHOD(thread_trunc_ln790_fu_355_p1);
    sensitive << ( ret_V_fu_341_p2 );

    SC_METHOD(thread_trunc_ln796_1_fu_389_p1);
    sensitive << ( lshr_ln808_fu_379_p2 );

    SC_METHOD(thread_trunc_ln796_fu_385_p1);
    sensitive << ( r_V_fu_369_p2 );

    SC_METHOD(thread_zext_ln1503_fu_269_p1);
    sensitive << ( codeword_length_histogram_V_q0 );

    SC_METHOD(thread_zext_ln215_fu_338_p1);
    sensitive << ( length_V_reg_492 );

    SC_METHOD(thread_zext_ln21_fu_264_p1);
    sensitive << ( i_0_reg_230 );

    SC_METHOD(thread_zext_ln28_fu_303_p1);
    sensitive << ( i1_0_reg_241 );

    SC_METHOD(thread_zext_ln544_fu_323_p1);
    sensitive << ( symbol_bits_V_q0 );

    SC_METHOD(thread_zext_ln556_fu_365_p1);
    sensitive << ( sub_ln556_fu_359_p2 );

    SC_METHOD(thread_zext_ln808_fu_375_p1);
    sensitive << ( ret_V_fu_341_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln18_fu_252_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln26_fu_291_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_block_state8_io );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_state9_io );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( regslice_both_encoding_V_data_V_U_apdone_blk );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "create_codeword_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, symbol_bits_V_address0, "(port)symbol_bits_V_address0");
    sc_trace(mVcdFile, symbol_bits_V_ce0, "(port)symbol_bits_V_ce0");
    sc_trace(mVcdFile, symbol_bits_V_q0, "(port)symbol_bits_V_q0");
    sc_trace(mVcdFile, codeword_length_histogram_V_address0, "(port)codeword_length_histogram_V_address0");
    sc_trace(mVcdFile, codeword_length_histogram_V_ce0, "(port)codeword_length_histogram_V_ce0");
    sc_trace(mVcdFile, codeword_length_histogram_V_q0, "(port)codeword_length_histogram_V_q0");
    sc_trace(mVcdFile, stream_buffer_user_V_address0, "(port)stream_buffer_user_V_address0");
    sc_trace(mVcdFile, stream_buffer_user_V_ce0, "(port)stream_buffer_user_V_ce0");
    sc_trace(mVcdFile, stream_buffer_user_V_q0, "(port)stream_buffer_user_V_q0");
    sc_trace(mVcdFile, stream_buffer_id_V_address0, "(port)stream_buffer_id_V_address0");
    sc_trace(mVcdFile, stream_buffer_id_V_ce0, "(port)stream_buffer_id_V_ce0");
    sc_trace(mVcdFile, stream_buffer_id_V_q0, "(port)stream_buffer_id_V_q0");
    sc_trace(mVcdFile, stream_buffer_dest_V_address0, "(port)stream_buffer_dest_V_address0");
    sc_trace(mVcdFile, stream_buffer_dest_V_ce0, "(port)stream_buffer_dest_V_ce0");
    sc_trace(mVcdFile, stream_buffer_dest_V_q0, "(port)stream_buffer_dest_V_q0");
    sc_trace(mVcdFile, encoding_TDATA, "(port)encoding_TDATA");
    sc_trace(mVcdFile, encoding_TVALID, "(port)encoding_TVALID");
    sc_trace(mVcdFile, encoding_TREADY, "(port)encoding_TREADY");
    sc_trace(mVcdFile, encoding_TKEEP, "(port)encoding_TKEEP");
    sc_trace(mVcdFile, encoding_TSTRB, "(port)encoding_TSTRB");
    sc_trace(mVcdFile, encoding_TUSER, "(port)encoding_TUSER");
    sc_trace(mVcdFile, encoding_TLAST, "(port)encoding_TLAST");
    sc_trace(mVcdFile, encoding_TID, "(port)encoding_TID");
    sc_trace(mVcdFile, encoding_TDEST, "(port)encoding_TDEST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, encoding_TDATA_blk_n, "encoding_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln26_reg_458, "icmp_ln26_reg_458");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, p_0199_0_reg_217, "p_0199_0_reg_217");
    sc_trace(mVcdFile, i_0_reg_230, "i_0_reg_230");
    sc_trace(mVcdFile, icmp_ln18_fu_252_p2, "icmp_ln18_fu_252_p2");
    sc_trace(mVcdFile, icmp_ln18_reg_428, "icmp_ln18_reg_428");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_258_p2, "i_fu_258_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, zext_ln21_fu_264_p1, "zext_ln21_fu_264_p1");
    sc_trace(mVcdFile, zext_ln21_reg_437, "zext_ln21_reg_437");
    sc_trace(mVcdFile, temp_V_fu_283_p3, "temp_V_fu_283_p3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, icmp_ln26_fu_291_p2, "icmp_ln26_fu_291_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_4_fu_297_p2, "i_4_fu_297_p2");
    sc_trace(mVcdFile, i_4_reg_462, "i_4_reg_462");
    sc_trace(mVcdFile, result_last_V_fu_311_p2, "result_last_V_fu_311_p2");
    sc_trace(mVcdFile, result_last_V_reg_477, "result_last_V_reg_477");
    sc_trace(mVcdFile, length_V_reg_492, "length_V_reg_492");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln883_fu_317_p2, "icmp_ln883_fu_317_p2");
    sc_trace(mVcdFile, icmp_ln883_reg_498, "icmp_ln883_reg_498");
    sc_trace(mVcdFile, first_codeword_V_add_1_reg_502, "first_codeword_V_add_1_reg_502");
    sc_trace(mVcdFile, result_user_V_reg_507, "result_user_V_reg_507");
    sc_trace(mVcdFile, result_id_V_reg_512, "result_id_V_reg_512");
    sc_trace(mVcdFile, result_dest_V_reg_517, "result_dest_V_reg_517");
    sc_trace(mVcdFile, ap_block_state8_io, "ap_block_state8_io");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, first_codeword_V_address0, "first_codeword_V_address0");
    sc_trace(mVcdFile, first_codeword_V_ce0, "first_codeword_V_ce0");
    sc_trace(mVcdFile, first_codeword_V_we0, "first_codeword_V_we0");
    sc_trace(mVcdFile, first_codeword_V_d0, "first_codeword_V_d0");
    sc_trace(mVcdFile, first_codeword_V_q0, "first_codeword_V_q0");
    sc_trace(mVcdFile, i1_0_reg_241, "i1_0_reg_241");
    sc_trace(mVcdFile, ap_block_state9_io, "ap_block_state9_io");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln28_fu_303_p1, "zext_ln28_fu_303_p1");
    sc_trace(mVcdFile, zext_ln544_fu_323_p1, "zext_ln544_fu_323_p1");
    sc_trace(mVcdFile, tmp_data_V_fu_102, "tmp_data_V_fu_102");
    sc_trace(mVcdFile, result_data_V_fu_408_p1, "result_data_V_fu_408_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, add_ln700_fu_412_p2, "add_ln700_fu_412_p2");
    sc_trace(mVcdFile, trunc_ln1503_fu_273_p1, "trunc_ln1503_fu_273_p1");
    sc_trace(mVcdFile, zext_ln1503_fu_269_p1, "zext_ln1503_fu_269_p1");
    sc_trace(mVcdFile, add_ln1503_fu_277_p2, "add_ln1503_fu_277_p2");
    sc_trace(mVcdFile, zext_ln215_fu_338_p1, "zext_ln215_fu_338_p1");
    sc_trace(mVcdFile, ret_V_fu_341_p2, "ret_V_fu_341_p2");
    sc_trace(mVcdFile, trunc_ln790_fu_355_p1, "trunc_ln790_fu_355_p1");
    sc_trace(mVcdFile, sub_ln556_fu_359_p2, "sub_ln556_fu_359_p2");
    sc_trace(mVcdFile, p_Result_s_fu_328_p4, "p_Result_s_fu_328_p4");
    sc_trace(mVcdFile, zext_ln556_fu_365_p1, "zext_ln556_fu_365_p1");
    sc_trace(mVcdFile, zext_ln808_fu_375_p1, "zext_ln808_fu_375_p1");
    sc_trace(mVcdFile, r_V_fu_369_p2, "r_V_fu_369_p2");
    sc_trace(mVcdFile, lshr_ln808_fu_379_p2, "lshr_ln808_fu_379_p2");
    sc_trace(mVcdFile, p_Result_1_fu_347_p3, "p_Result_1_fu_347_p3");
    sc_trace(mVcdFile, trunc_ln796_fu_385_p1, "trunc_ln796_fu_385_p1");
    sc_trace(mVcdFile, trunc_ln796_1_fu_389_p1, "trunc_ln796_1_fu_389_p1");
    sc_trace(mVcdFile, select_ln796_fu_393_p3, "select_ln796_fu_393_p3");
    sc_trace(mVcdFile, tmp_2_fu_401_p3, "tmp_2_fu_401_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, regslice_both_encoding_V_data_V_U_apdone_blk, "regslice_both_encoding_V_data_V_U_apdone_blk");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, encoding_TVALID_int, "encoding_TVALID_int");
    sc_trace(mVcdFile, encoding_TREADY_int, "encoding_TREADY_int");
    sc_trace(mVcdFile, regslice_both_encoding_V_data_V_U_vld_out, "regslice_both_encoding_V_data_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_encoding_V_keep_V_U_apdone_blk, "regslice_both_encoding_V_keep_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_encoding_V_keep_V_U_ack_in_dummy, "regslice_both_encoding_V_keep_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_encoding_V_keep_V_U_vld_out, "regslice_both_encoding_V_keep_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_encoding_V_strb_V_U_apdone_blk, "regslice_both_encoding_V_strb_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_encoding_V_strb_V_U_ack_in_dummy, "regslice_both_encoding_V_strb_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_encoding_V_strb_V_U_vld_out, "regslice_both_encoding_V_strb_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_encoding_V_user_V_U_apdone_blk, "regslice_both_encoding_V_user_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_encoding_V_user_V_U_ack_in_dummy, "regslice_both_encoding_V_user_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_encoding_V_user_V_U_vld_out, "regslice_both_encoding_V_user_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_encoding_V_last_V_U_apdone_blk, "regslice_both_encoding_V_last_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_encoding_V_last_V_U_ack_in_dummy, "regslice_both_encoding_V_last_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_encoding_V_last_V_U_vld_out, "regslice_both_encoding_V_last_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_encoding_V_id_V_U_apdone_blk, "regslice_both_encoding_V_id_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_encoding_V_id_V_U_ack_in_dummy, "regslice_both_encoding_V_id_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_encoding_V_id_V_U_vld_out, "regslice_both_encoding_V_id_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_encoding_V_dest_V_U_apdone_blk, "regslice_both_encoding_V_dest_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_encoding_V_dest_V_U_ack_in_dummy, "regslice_both_encoding_V_dest_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_encoding_V_dest_V_U_vld_out, "regslice_both_encoding_V_dest_V_U_vld_out");
#endif

    }
}

create_codeword::~create_codeword() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete first_codeword_V_U;
    delete regslice_both_encoding_V_data_V_U;
    delete regslice_both_encoding_V_keep_V_U;
    delete regslice_both_encoding_V_strb_V_U;
    delete regslice_both_encoding_V_user_V_U;
    delete regslice_both_encoding_V_last_V_U;
    delete regslice_both_encoding_V_id_V_U;
    delete regslice_both_encoding_V_dest_V_U;
}

void create_codeword::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv4_F;
}

void create_codeword::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                    esl_seteq<1,1,1>(regslice_both_encoding_V_data_V_U_apdone_blk.read(), ap_const_logic_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i1_0_reg_241 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(icmp_ln26_reg_458.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(ap_block_state9_io.read(), ap_const_boolean_0))) {
        i1_0_reg_241 = i_4_reg_462.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_reg_230 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln18_fu_252_p2.read()))) {
        i_0_reg_230 = i_fu_258_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_0199_0_reg_217 = ap_const_lv27_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln18_reg_428.read()))) {
        p_0199_0_reg_217 = temp_V_fu_283_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln883_fu_317_p2.read()))) {
        first_codeword_V_add_1_reg_502 =  (sc_lv<5>) (zext_ln544_fu_323_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_4_reg_462 = i_4_fu_297_p2.read();
        icmp_ln26_reg_458 = icmp_ln26_fu_291_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln18_reg_428 = icmp_ln18_fu_252_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        icmp_ln883_reg_498 = icmp_ln883_fu_317_p2.read();
        length_V_reg_492 = symbol_bits_V_q0.read();
        result_dest_V_reg_517 = stream_buffer_dest_V_q0.read();
        result_id_V_reg_512 = stream_buffer_id_V_q0.read();
        result_user_V_reg_507 = stream_buffer_user_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln26_fu_291_p2.read()))) {
        result_last_V_reg_477 = result_last_V_fu_311_p2.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln26_reg_458.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln883_reg_498.read()))) {
        tmp_data_V_fu_102 = result_data_V_fu_408_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln18_fu_252_p2.read()))) {
        zext_ln21_reg_437 = zext_ln21_fu_264_p1.read();
    }
}

void create_codeword::thread_add_ln1503_fu_277_p2() {
    add_ln1503_fu_277_p2 = (!trunc_ln1503_fu_273_p1.read().is_01() || !zext_ln1503_fu_269_p1.read().is_01())? sc_lv<26>(): (sc_biguint<26>(trunc_ln1503_fu_273_p1.read()) + sc_biguint<26>(zext_ln1503_fu_269_p1.read()));
}

void create_codeword::thread_add_ln700_fu_412_p2() {
    add_ln700_fu_412_p2 = (!ap_const_lv27_1.is_01() || !first_codeword_V_q0.read().is_01())? sc_lv<27>(): (sc_biguint<27>(ap_const_lv27_1) + sc_biguint<27>(first_codeword_V_q0.read()));
}

void create_codeword::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void create_codeword::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void create_codeword::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[8];
}

void create_codeword::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void create_codeword::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void create_codeword::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void create_codeword::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void create_codeword::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[6];
}

void create_codeword::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[7];
}

void create_codeword::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void create_codeword::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void create_codeword::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void create_codeword::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void create_codeword::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void create_codeword::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void create_codeword::thread_ap_block_state8_io() {
    ap_block_state8_io = (esl_seteq<1,1,1>(icmp_ln26_reg_458.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, encoding_TREADY_int.read()));
}

void create_codeword::thread_ap_block_state9_io() {
    ap_block_state9_io = (esl_seteq<1,1,1>(icmp_ln26_reg_458.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, encoding_TREADY_int.read()));
}

void create_codeword::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln18_fu_252_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void create_codeword::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(regslice_both_encoding_V_data_V_U_apdone_blk.read(), ap_const_logic_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void create_codeword::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void create_codeword::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void create_codeword::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void create_codeword::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(regslice_both_encoding_V_data_V_U_apdone_blk.read(), ap_const_logic_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void create_codeword::thread_codeword_length_histogram_V_address0() {
    codeword_length_histogram_V_address0 =  (sc_lv<6>) (zext_ln21_fu_264_p1.read());
}

void create_codeword::thread_codeword_length_histogram_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        codeword_length_histogram_V_ce0 = ap_const_logic_1;
    } else {
        codeword_length_histogram_V_ce0 = ap_const_logic_0;
    }
}

void create_codeword::thread_encoding_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(icmp_ln26_reg_458.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(icmp_ln26_reg_458.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())))) {
        encoding_TDATA_blk_n = encoding_TREADY_int.read();
    } else {
        encoding_TDATA_blk_n = ap_const_logic_1;
    }
}

void create_codeword::thread_encoding_TVALID() {
    encoding_TVALID = regslice_both_encoding_V_data_V_U_vld_out.read();
}

void create_codeword::thread_encoding_TVALID_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln26_reg_458.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_state8_io.read(), ap_const_boolean_0))) {
        encoding_TVALID_int = ap_const_logic_1;
    } else {
        encoding_TVALID_int = ap_const_logic_0;
    }
}

void create_codeword::thread_first_codeword_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        first_codeword_V_address0 = first_codeword_V_add_1_reg_502.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        first_codeword_V_address0 =  (sc_lv<5>) (zext_ln544_fu_323_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        first_codeword_V_address0 =  (sc_lv<5>) (zext_ln21_reg_437.read());
    } else {
        first_codeword_V_address0 = "XXXXX";
    }
}

void create_codeword::thread_first_codeword_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        first_codeword_V_ce0 = ap_const_logic_1;
    } else {
        first_codeword_V_ce0 = ap_const_logic_0;
    }
}

void create_codeword::thread_first_codeword_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        first_codeword_V_d0 = add_ln700_fu_412_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        first_codeword_V_d0 = p_0199_0_reg_217.read();
    } else {
        first_codeword_V_d0 =  (sc_lv<27>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void create_codeword::thread_first_codeword_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln18_reg_428.read())) || 
         (esl_seteq<1,1,1>(icmp_ln26_reg_458.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln883_reg_498.read())))) {
        first_codeword_V_we0 = ap_const_logic_1;
    } else {
        first_codeword_V_we0 = ap_const_logic_0;
    }
}

void create_codeword::thread_i_4_fu_297_p2() {
    i_4_fu_297_p2 = (!i1_0_reg_241.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i1_0_reg_241.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void create_codeword::thread_i_fu_258_p2() {
    i_fu_258_p2 = (!i_0_reg_230.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_reg_230.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void create_codeword::thread_icmp_ln18_fu_252_p2() {
    icmp_ln18_fu_252_p2 = (!i_0_reg_230.read().is_01() || !ap_const_lv5_1B.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_230.read() == ap_const_lv5_1B);
}

void create_codeword::thread_icmp_ln26_fu_291_p2() {
    icmp_ln26_fu_291_p2 = (!i1_0_reg_241.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_241.read() == ap_const_lv9_100);
}

void create_codeword::thread_icmp_ln883_fu_317_p2() {
    icmp_ln883_fu_317_p2 = (!symbol_bits_V_q0.read().is_01() || !ap_const_lv5_0.is_01())? sc_lv<1>(): sc_lv<1>(symbol_bits_V_q0.read() == ap_const_lv5_0);
}

void create_codeword::thread_lshr_ln808_fu_379_p2() {
    lshr_ln808_fu_379_p2 = (!zext_ln808_fu_375_p1.read().is_01())? sc_lv<27>(): p_Result_s_fu_328_p4.read() >> (unsigned short)zext_ln808_fu_375_p1.read().to_uint();
}

void create_codeword::thread_p_Result_1_fu_347_p3() {
    p_Result_1_fu_347_p3 = ret_V_fu_341_p2.read().range(5, 5);
}

void create_codeword::thread_p_Result_s_fu_328_p4() {
    p_Result_s_fu_328_p4 = first_codeword_V_q0.read().range(0, 26);
}

void create_codeword::thread_r_V_fu_369_p2() {
    r_V_fu_369_p2 = (!zext_ln556_fu_365_p1.read().is_01())? sc_lv<27>(): p_Result_s_fu_328_p4.read() << (unsigned short)zext_ln556_fu_365_p1.read().to_uint();
}

void create_codeword::thread_result_data_V_fu_408_p1() {
    result_data_V_fu_408_p1 = esl_zext<32,27>(tmp_2_fu_401_p3.read());
}

void create_codeword::thread_result_last_V_fu_311_p2() {
    result_last_V_fu_311_p2 = (!i1_0_reg_241.read().is_01() || !ap_const_lv9_FF.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_241.read() == ap_const_lv9_FF);
}

void create_codeword::thread_ret_V_fu_341_p2() {
    ret_V_fu_341_p2 = (!ap_const_lv6_1B.is_01() || !zext_ln215_fu_338_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1B) - sc_biguint<6>(zext_ln215_fu_338_p1.read()));
}

void create_codeword::thread_select_ln796_fu_393_p3() {
    select_ln796_fu_393_p3 = (!p_Result_1_fu_347_p3.read()[0].is_01())? sc_lv<22>(): ((p_Result_1_fu_347_p3.read()[0].to_bool())? trunc_ln796_fu_385_p1.read(): trunc_ln796_1_fu_389_p1.read());
}

void create_codeword::thread_stream_buffer_dest_V_address0() {
    stream_buffer_dest_V_address0 =  (sc_lv<8>) (zext_ln28_fu_303_p1.read());
}

void create_codeword::thread_stream_buffer_dest_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        stream_buffer_dest_V_ce0 = ap_const_logic_1;
    } else {
        stream_buffer_dest_V_ce0 = ap_const_logic_0;
    }
}

void create_codeword::thread_stream_buffer_id_V_address0() {
    stream_buffer_id_V_address0 =  (sc_lv<8>) (zext_ln28_fu_303_p1.read());
}

void create_codeword::thread_stream_buffer_id_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        stream_buffer_id_V_ce0 = ap_const_logic_1;
    } else {
        stream_buffer_id_V_ce0 = ap_const_logic_0;
    }
}

void create_codeword::thread_stream_buffer_user_V_address0() {
    stream_buffer_user_V_address0 =  (sc_lv<8>) (zext_ln28_fu_303_p1.read());
}

void create_codeword::thread_stream_buffer_user_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        stream_buffer_user_V_ce0 = ap_const_logic_1;
    } else {
        stream_buffer_user_V_ce0 = ap_const_logic_0;
    }
}

void create_codeword::thread_sub_ln556_fu_359_p2() {
    sub_ln556_fu_359_p2 = (!ap_const_lv3_0.is_01() || !trunc_ln790_fu_355_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_0) - sc_biguint<3>(trunc_ln790_fu_355_p1.read()));
}

void create_codeword::thread_symbol_bits_V_address0() {
    symbol_bits_V_address0 =  (sc_lv<8>) (zext_ln28_fu_303_p1.read());
}

void create_codeword::thread_symbol_bits_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        symbol_bits_V_ce0 = ap_const_logic_1;
    } else {
        symbol_bits_V_ce0 = ap_const_logic_0;
    }
}

void create_codeword::thread_temp_V_fu_283_p3() {
    temp_V_fu_283_p3 = esl_concat<26,1>(add_ln1503_fu_277_p2.read(), ap_const_lv1_0);
}

void create_codeword::thread_tmp_2_fu_401_p3() {
    tmp_2_fu_401_p3 = esl_concat<22,5>(select_ln796_fu_393_p3.read(), length_V_reg_492.read());
}

void create_codeword::thread_trunc_ln1503_fu_273_p1() {
    trunc_ln1503_fu_273_p1 = p_0199_0_reg_217.read().range(26-1, 0);
}

void create_codeword::thread_trunc_ln790_fu_355_p1() {
    trunc_ln790_fu_355_p1 = ret_V_fu_341_p2.read().range(3-1, 0);
}

void create_codeword::thread_trunc_ln796_1_fu_389_p1() {
    trunc_ln796_1_fu_389_p1 = lshr_ln808_fu_379_p2.read().range(22-1, 0);
}

void create_codeword::thread_trunc_ln796_fu_385_p1() {
    trunc_ln796_fu_385_p1 = r_V_fu_369_p2.read().range(22-1, 0);
}

void create_codeword::thread_zext_ln1503_fu_269_p1() {
    zext_ln1503_fu_269_p1 = esl_zext<26,9>(codeword_length_histogram_V_q0.read());
}

void create_codeword::thread_zext_ln215_fu_338_p1() {
    zext_ln215_fu_338_p1 = esl_zext<6,5>(length_V_reg_492.read());
}

void create_codeword::thread_zext_ln21_fu_264_p1() {
    zext_ln21_fu_264_p1 = esl_zext<64,5>(i_0_reg_230.read());
}

void create_codeword::thread_zext_ln28_fu_303_p1() {
    zext_ln28_fu_303_p1 = esl_zext<64,9>(i1_0_reg_241.read());
}

void create_codeword::thread_zext_ln544_fu_323_p1() {
    zext_ln544_fu_323_p1 = esl_zext<64,5>(symbol_bits_V_q0.read());
}

void create_codeword::thread_zext_ln556_fu_365_p1() {
    zext_ln556_fu_365_p1 = esl_zext<27,3>(sub_ln556_fu_359_p2.read());
}

void create_codeword::thread_zext_ln808_fu_375_p1() {
    zext_ln808_fu_375_p1 = esl_zext<27,6>(ret_V_fu_341_p2.read());
}

void create_codeword::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln18_fu_252_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln18_fu_252_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln26_fu_291_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_block_state8_io.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_block_state9_io.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(regslice_both_encoding_V_data_V_U_apdone_blk.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

