// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "create_tree.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic create_tree::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic create_tree::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> create_tree::ap_ST_fsm_state1 = "1";
const sc_lv<8> create_tree::ap_ST_fsm_state2 = "10";
const sc_lv<8> create_tree::ap_ST_fsm_state3 = "100";
const sc_lv<8> create_tree::ap_ST_fsm_state4 = "1000";
const sc_lv<8> create_tree::ap_ST_fsm_state5 = "10000";
const sc_lv<8> create_tree::ap_ST_fsm_state6 = "100000";
const sc_lv<8> create_tree::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> create_tree::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> create_tree::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool create_tree::ap_const_boolean_1 = true;
const sc_lv<32> create_tree::ap_const_lv32_1 = "1";
const sc_lv<32> create_tree::ap_const_lv32_4 = "100";
const sc_lv<1> create_tree::ap_const_lv1_1 = "1";
const sc_lv<32> create_tree::ap_const_lv32_6 = "110";
const sc_lv<32> create_tree::ap_const_lv32_2 = "10";
const sc_lv<32> create_tree::ap_const_lv32_3 = "11";
const sc_lv<1> create_tree::ap_const_lv1_0 = "0";
const sc_lv<32> create_tree::ap_const_lv32_5 = "101";
const sc_lv<9> create_tree::ap_const_lv9_0 = "000000000";
const sc_lv<32> create_tree::ap_const_lv32_7 = "111";
const sc_lv<9> create_tree::ap_const_lv9_1FF = "111111111";
const sc_lv<32> create_tree::ap_const_lv32_8 = "1000";
const sc_lv<10> create_tree::ap_const_lv10_3FF = "1111111111";
const sc_lv<9> create_tree::ap_const_lv9_1 = "1";
const sc_lv<10> create_tree::ap_const_lv10_1 = "1";
const sc_lv<32> create_tree::ap_const_lv32_9 = "1001";

create_tree::create_tree(sc_module_name name) : sc_module(name), mVcdFile(0) {
    frequency_0_V_U = new create_tree_frequhbi("frequency_0_V_U");
    frequency_0_V_U->clk(ap_clk);
    frequency_0_V_U->reset(ap_rst);
    frequency_0_V_U->address0(frequency_0_V_address0);
    frequency_0_V_U->ce0(frequency_0_V_ce0);
    frequency_0_V_U->we0(frequency_0_V_we0);
    frequency_0_V_U->d0(frequency_0_V_d0);
    frequency_0_V_U->q0(frequency_0_V_q0);
    frequency_0_V_U->address1(frequency_0_V_address1);
    frequency_0_V_U->ce1(frequency_0_V_ce1);
    frequency_0_V_U->q1(frequency_0_V_q1);
    frequency_1_V_U = new create_tree_frequibs("frequency_1_V_U");
    frequency_1_V_U->clk(ap_clk);
    frequency_1_V_U->reset(ap_rst);
    frequency_1_V_U->address0(frequency_1_V_address0);
    frequency_1_V_U->ce0(frequency_1_V_ce0);
    frequency_1_V_U->we0(frequency_1_V_we0);
    frequency_1_V_U->d0(frequency_1_V_d0);
    frequency_1_V_U->q0(frequency_1_V_q0);
    frequency_1_V_U->address1(frequency_1_V_address1);
    frequency_1_V_U->ce1(frequency_1_V_ce1);
    frequency_1_V_U->q1(frequency_1_V_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln209_1_fu_675_p2);
    sensitive << ( p_0195_0_i_i_reg_392 );
    sensitive << ( p_0120_0_i_i_reg_402 );

    SC_METHOD(thread_add_ln209_fu_704_p2);
    sensitive << ( s_1_1_i_i_reg_345 );
    sensitive << ( p_0195_0_i_i_reg_392 );

    SC_METHOD(thread_add_ln21_fu_500_p2);
    sensitive << ( extLd_cast_fu_497_p1 );

    SC_METHOD(thread_and_ln34_fu_605_p2);
    sensitive << ( xor_ln34_fu_599_p2 );
    sensitive << ( icmp_ln34_fu_588_p2 );

    SC_METHOD(thread_and_ln52_fu_657_p2);
    sensitive << ( xor_ln52_fu_651_p2 );
    sensitive << ( icmp_ln52_fu_640_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( extLd_loc_empty_n );
    sensitive << ( extLd_loc_out_full_n );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );

    SC_METHOD(thread_ap_block_state5);
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( ap_predicate_op78_read_state5 );
    sensitive << ( ap_predicate_op79_read_state5 );

    SC_METHOD(thread_ap_block_state7);
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( ap_predicate_op127_read_state7 );
    sensitive << ( ap_predicate_op128_read_state7 );

    SC_METHOD(thread_ap_condition_184);
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( ap_predicate_op78_read_state5 );
    sensitive << ( ap_predicate_op79_read_state5 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4);
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( or_ln52_reg_840 );
    sensitive << ( t_V_4_reg_370 );
    sensitive << ( p_0217_2_i_i_reg_463 );

    SC_METHOD(thread_ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4);
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( or_ln52_reg_840 );
    sensitive << ( in_count_V_1_fu_722_p2 );
    sensitive << ( p_0247_2_i_i_reg_475 );

    SC_METHOD(thread_ap_phi_mux_s_0_2_i_i_phi_fu_454_p4);
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( or_ln52_reg_840 );
    sensitive << ( s_value_V_2_reg_334 );
    sensitive << ( s_0_2_i_i_reg_450 );

    SC_METHOD(thread_ap_phi_mux_s_1_2_i_i_phi_fu_441_p4);
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( or_ln52_reg_840 );
    sensitive << ( s_frequency_V_2_reg_323 );
    sensitive << ( s_1_2_i_i_reg_437 );

    SC_METHOD(thread_ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4);
    sensitive << ( in_value_V_dout );
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( or_ln52_reg_840 );
    sensitive << ( s_next_0_2_i_i_reg_424 );

    SC_METHOD(thread_ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4);
    sensitive << ( in_frequency_V_dout );
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( or_ln52_reg_840 );
    sensitive << ( s_next_1_2_i_i_reg_411 );

    SC_METHOD(thread_ap_predicate_op127_read_state7);
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( or_ln52_reg_840 );

    SC_METHOD(thread_ap_predicate_op128_read_state7);
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( or_ln52_reg_840 );

    SC_METHOD(thread_ap_predicate_op78_read_state5);
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( or_ln34_reg_806 );

    SC_METHOD(thread_ap_predicate_op79_read_state5);
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( or_ln34_reg_806 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_extLd_cast_fu_497_p1);
    sensitive << ( extLd_loc_read_reg_734 );

    SC_METHOD(thread_extLd_loc_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( extLd_loc_empty_n );

    SC_METHOD(thread_extLd_loc_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( extLd_loc_out_full_n );

    SC_METHOD(thread_extLd_loc_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( extLd_loc_dout );
    sensitive << ( extLd_loc_empty_n );
    sensitive << ( extLd_loc_out_full_n );

    SC_METHOD(thread_extLd_loc_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( extLd_loc_empty_n );
    sensitive << ( extLd_loc_out_full_n );

    SC_METHOD(thread_extLd_loc_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( extLd_loc_empty_n );
    sensitive << ( extLd_loc_out_full_n );

    SC_METHOD(thread_frequency_0_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln31_fu_531_p1 );
    sensitive << ( zext_ln321_1_fu_687_p1 );
    sensitive << ( zext_ln321_fu_716_p1 );
    sensitive << ( trunc_ln321_1_fu_683_p1 );
    sensitive << ( trunc_ln321_fu_712_p1 );

    SC_METHOD(thread_frequency_0_V_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln32_fu_557_p1 );

    SC_METHOD(thread_frequency_0_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln321_1_fu_683_p1 );
    sensitive << ( trunc_ln321_fu_712_p1 );

    SC_METHOD(thread_frequency_0_V_ce1);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_frequency_0_V_d0);
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln321_1_fu_683_p1 );
    sensitive << ( add_ln209_1_fu_675_p2 );
    sensitive << ( trunc_ln321_fu_712_p1 );
    sensitive << ( add_ln209_fu_704_p2 );

    SC_METHOD(thread_frequency_0_V_we0);
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln321_1_fu_683_p1 );
    sensitive << ( trunc_ln321_fu_712_p1 );

    SC_METHOD(thread_frequency_1_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln31_fu_531_p1 );
    sensitive << ( zext_ln321_1_fu_687_p1 );
    sensitive << ( zext_ln321_fu_716_p1 );
    sensitive << ( trunc_ln321_1_fu_683_p1 );
    sensitive << ( trunc_ln321_fu_712_p1 );

    SC_METHOD(thread_frequency_1_V_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln32_fu_557_p1 );

    SC_METHOD(thread_frequency_1_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln321_1_fu_683_p1 );
    sensitive << ( trunc_ln321_fu_712_p1 );

    SC_METHOD(thread_frequency_1_V_ce1);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_frequency_1_V_d0);
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln321_1_fu_683_p1 );
    sensitive << ( add_ln209_1_fu_675_p2 );
    sensitive << ( trunc_ln321_fu_712_p1 );
    sensitive << ( add_ln209_fu_704_p2 );

    SC_METHOD(thread_frequency_1_V_we0);
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln321_1_fu_683_p1 );
    sensitive << ( trunc_ln321_fu_712_p1 );

    SC_METHOD(thread_grp_fu_487_p4);
    sensitive << ( op_assign_reg_310 );

    SC_METHOD(thread_i_fu_515_p2);
    sensitive << ( op_assign_reg_310 );

    SC_METHOD(thread_icmp_ln21_fu_510_p2);
    sensitive << ( add_ln21_reg_761 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln243_fu_506_p1 );

    SC_METHOD(thread_icmp_ln34_1_fu_593_p2);
    sensitive << ( intermediate_freq_V_1_fu_572_p3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( node_freq_V_reg_265 );

    SC_METHOD(thread_icmp_ln34_fu_588_p2);
    sensitive << ( extLd_loc_read_reg_734 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( t_V_reg_298 );

    SC_METHOD(thread_icmp_ln52_1_fu_645_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( s_1_1_i_i_reg_345 );
    sensitive << ( p_0120_0_i_i_reg_402 );

    SC_METHOD(thread_icmp_ln52_fu_640_p2);
    sensitive << ( extLd_loc_read_reg_734 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( t_V_3_reg_381 );

    SC_METHOD(thread_icmp_ln879_3_fu_663_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( op_assign_reg_310 );
    sensitive << ( t_V_4_reg_370 );

    SC_METHOD(thread_icmp_ln879_fu_611_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( t_V_2_reg_286 );
    sensitive << ( op_assign_reg_310 );

    SC_METHOD(thread_in_count_V_1_fu_722_p2);
    sensitive << ( t_V_3_reg_381 );

    SC_METHOD(thread_in_count_V_fu_634_p2);
    sensitive << ( t_V_reg_298 );

    SC_METHOD(thread_in_frequency_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( or_ln34_reg_806 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( or_ln52_reg_840 );

    SC_METHOD(thread_in_frequency_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( extLd_loc_empty_n );
    sensitive << ( extLd_loc_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_predicate_op78_read_state5 );
    sensitive << ( ap_predicate_op79_read_state5 );
    sensitive << ( ap_predicate_op127_read_state7 );
    sensitive << ( ap_predicate_op128_read_state7 );

    SC_METHOD(thread_in_value_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_value_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln21_reg_766 );
    sensitive << ( or_ln34_reg_806 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( or_ln52_reg_840 );

    SC_METHOD(thread_in_value_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( extLd_loc_empty_n );
    sensitive << ( extLd_loc_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_predicate_op78_read_state5 );
    sensitive << ( ap_predicate_op79_read_state5 );
    sensitive << ( ap_predicate_op127_read_state7 );
    sensitive << ( ap_predicate_op128_read_state7 );

    SC_METHOD(thread_intermediate_freq_V_1_fu_572_p3);
    sensitive << ( frequency_0_V_q0 );
    sensitive << ( frequency_1_V_q0 );
    sensitive << ( trunc_ln31_fu_568_p1 );

    SC_METHOD(thread_intermediate_freq_ne_fu_580_p3);
    sensitive << ( frequency_0_V_q1 );
    sensitive << ( frequency_1_V_q1 );
    sensitive << ( trunc_ln31_fu_568_p1 );

    SC_METHOD(thread_left_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( or_ln34_fu_617_p2 );
    sensitive << ( zext_ln36_fu_623_p1 );

    SC_METHOD(thread_left_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( or_ln34_fu_617_p2 );

    SC_METHOD(thread_left_V_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( or_ln34_fu_617_p2 );
    sensitive << ( s_0_0_i_i_reg_275 );

    SC_METHOD(thread_left_V_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( or_ln34_fu_617_p2 );

    SC_METHOD(thread_lshr_ln1_fu_547_p4);
    sensitive << ( ret_V_fu_541_p2 );

    SC_METHOD(thread_lshr_ln_fu_521_p4);
    sensitive << ( t_V_2_reg_286 );

    SC_METHOD(thread_or_ln34_fu_617_p2);
    sensitive << ( and_ln34_fu_605_p2 );
    sensitive << ( icmp_ln879_fu_611_p2 );

    SC_METHOD(thread_or_ln52_fu_669_p2);
    sensitive << ( and_ln52_fu_657_p2 );
    sensitive << ( icmp_ln879_3_fu_663_p2 );

    SC_METHOD(thread_parent_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln544_fu_563_p1 );
    sensitive << ( zext_ln544_4_fu_693_p1 );
    sensitive << ( zext_ln544_3_fu_729_p1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_parent_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_parent_V_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( op_assign_reg_310 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_parent_V_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( or_ln34_fu_617_p2 );
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ret_V_fu_541_p2);
    sensitive << ( zext_ln215_fu_537_p1 );

    SC_METHOD(thread_right_V_address0);
    sensitive << ( right_V_addr_reg_835 );
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_right_V_ce0);
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_right_V_d0);
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( s_0_1_i_i_reg_357 );

    SC_METHOD(thread_right_V_we0);
    sensitive << ( or_ln52_fu_669_p2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tree_count_V_1_fu_698_p2);
    sensitive << ( t_V_4_reg_370 );

    SC_METHOD(thread_tree_count_V_fu_628_p2);
    sensitive << ( t_V_2_reg_286 );

    SC_METHOD(thread_trunc_ln31_fu_568_p1);
    sensitive << ( t_V_2_reg_286 );

    SC_METHOD(thread_trunc_ln321_1_fu_683_p1);
    sensitive << ( op_assign_reg_310 );

    SC_METHOD(thread_trunc_ln321_fu_712_p1);
    sensitive << ( op_assign_reg_310 );

    SC_METHOD(thread_xor_ln34_fu_599_p2);
    sensitive << ( icmp_ln34_1_fu_593_p2 );

    SC_METHOD(thread_xor_ln52_fu_651_p2);
    sensitive << ( icmp_ln52_1_fu_645_p2 );

    SC_METHOD(thread_zext_ln215_fu_537_p1);
    sensitive << ( t_V_2_reg_286 );

    SC_METHOD(thread_zext_ln243_fu_506_p1);
    sensitive << ( op_assign_reg_310 );

    SC_METHOD(thread_zext_ln31_fu_531_p1);
    sensitive << ( lshr_ln_fu_521_p4 );

    SC_METHOD(thread_zext_ln321_1_fu_687_p1);
    sensitive << ( grp_fu_487_p4 );

    SC_METHOD(thread_zext_ln321_fu_716_p1);
    sensitive << ( grp_fu_487_p4 );

    SC_METHOD(thread_zext_ln32_fu_557_p1);
    sensitive << ( lshr_ln1_fu_547_p4 );

    SC_METHOD(thread_zext_ln36_fu_623_p1);
    sensitive << ( op_assign_reg_310 );

    SC_METHOD(thread_zext_ln544_3_fu_729_p1);
    sensitive << ( t_V_2_reg_286 );

    SC_METHOD(thread_zext_ln544_4_fu_693_p1);
    sensitive << ( t_V_4_reg_370 );

    SC_METHOD(thread_zext_ln544_fu_563_p1);
    sensitive << ( t_V_2_reg_286 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_value_V_empty_n );
    sensitive << ( in_frequency_V_empty_n );
    sensitive << ( extLd_loc_empty_n );
    sensitive << ( extLd_loc_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln21_fu_510_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_predicate_op78_read_state5 );
    sensitive << ( ap_predicate_op79_read_state5 );
    sensitive << ( ap_predicate_op127_read_state7 );
    sensitive << ( ap_predicate_op128_read_state7 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "create_tree_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_value_V_dout, "(port)in_value_V_dout");
    sc_trace(mVcdFile, in_value_V_empty_n, "(port)in_value_V_empty_n");
    sc_trace(mVcdFile, in_value_V_read, "(port)in_value_V_read");
    sc_trace(mVcdFile, in_frequency_V_dout, "(port)in_frequency_V_dout");
    sc_trace(mVcdFile, in_frequency_V_empty_n, "(port)in_frequency_V_empty_n");
    sc_trace(mVcdFile, in_frequency_V_read, "(port)in_frequency_V_read");
    sc_trace(mVcdFile, extLd_loc_dout, "(port)extLd_loc_dout");
    sc_trace(mVcdFile, extLd_loc_empty_n, "(port)extLd_loc_empty_n");
    sc_trace(mVcdFile, extLd_loc_read, "(port)extLd_loc_read");
    sc_trace(mVcdFile, parent_V_address0, "(port)parent_V_address0");
    sc_trace(mVcdFile, parent_V_ce0, "(port)parent_V_ce0");
    sc_trace(mVcdFile, parent_V_we0, "(port)parent_V_we0");
    sc_trace(mVcdFile, parent_V_d0, "(port)parent_V_d0");
    sc_trace(mVcdFile, left_V_address0, "(port)left_V_address0");
    sc_trace(mVcdFile, left_V_ce0, "(port)left_V_ce0");
    sc_trace(mVcdFile, left_V_we0, "(port)left_V_we0");
    sc_trace(mVcdFile, left_V_d0, "(port)left_V_d0");
    sc_trace(mVcdFile, right_V_address0, "(port)right_V_address0");
    sc_trace(mVcdFile, right_V_ce0, "(port)right_V_ce0");
    sc_trace(mVcdFile, right_V_we0, "(port)right_V_we0");
    sc_trace(mVcdFile, right_V_d0, "(port)right_V_d0");
    sc_trace(mVcdFile, extLd_loc_out_din, "(port)extLd_loc_out_din");
    sc_trace(mVcdFile, extLd_loc_out_full_n, "(port)extLd_loc_out_full_n");
    sc_trace(mVcdFile, extLd_loc_out_write, "(port)extLd_loc_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, in_value_V_blk_n, "in_value_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln21_reg_766, "icmp_ln21_reg_766");
    sc_trace(mVcdFile, or_ln34_reg_806, "or_ln34_reg_806");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, or_ln52_reg_840, "or_ln52_reg_840");
    sc_trace(mVcdFile, in_frequency_V_blk_n, "in_frequency_V_blk_n");
    sc_trace(mVcdFile, extLd_loc_blk_n, "extLd_loc_blk_n");
    sc_trace(mVcdFile, extLd_loc_out_blk_n, "extLd_loc_out_blk_n");
    sc_trace(mVcdFile, extLd_loc_read_reg_734, "extLd_loc_read_reg_734");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, s_value_V_reg_741, "s_value_V_reg_741");
    sc_trace(mVcdFile, s_frequency_V_reg_746, "s_frequency_V_reg_746");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, add_ln21_fu_500_p2, "add_ln21_fu_500_p2");
    sc_trace(mVcdFile, add_ln21_reg_761, "add_ln21_reg_761");
    sc_trace(mVcdFile, icmp_ln21_fu_510_p2, "icmp_ln21_fu_510_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_fu_515_p2, "i_fu_515_p2");
    sc_trace(mVcdFile, i_reg_770, "i_reg_770");
    sc_trace(mVcdFile, intermediate_freq_V_1_fu_572_p3, "intermediate_freq_V_1_fu_572_p3");
    sc_trace(mVcdFile, intermediate_freq_V_1_reg_795, "intermediate_freq_V_1_reg_795");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, intermediate_freq_ne_fu_580_p3, "intermediate_freq_ne_fu_580_p3");
    sc_trace(mVcdFile, intermediate_freq_ne_reg_801, "intermediate_freq_ne_reg_801");
    sc_trace(mVcdFile, or_ln34_fu_617_p2, "or_ln34_fu_617_p2");
    sc_trace(mVcdFile, zext_ln36_fu_623_p1, "zext_ln36_fu_623_p1");
    sc_trace(mVcdFile, zext_ln36_reg_810, "zext_ln36_reg_810");
    sc_trace(mVcdFile, tree_count_V_fu_628_p2, "tree_count_V_fu_628_p2");
    sc_trace(mVcdFile, ap_predicate_op78_read_state5, "ap_predicate_op78_read_state5");
    sc_trace(mVcdFile, ap_predicate_op79_read_state5, "ap_predicate_op79_read_state5");
    sc_trace(mVcdFile, ap_block_state5, "ap_block_state5");
    sc_trace(mVcdFile, in_count_V_fu_634_p2, "in_count_V_fu_634_p2");
    sc_trace(mVcdFile, right_V_addr_reg_835, "right_V_addr_reg_835");
    sc_trace(mVcdFile, or_ln52_fu_669_p2, "or_ln52_fu_669_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tree_count_V_1_fu_698_p2, "tree_count_V_1_fu_698_p2");
    sc_trace(mVcdFile, frequency_0_V_address0, "frequency_0_V_address0");
    sc_trace(mVcdFile, frequency_0_V_ce0, "frequency_0_V_ce0");
    sc_trace(mVcdFile, frequency_0_V_we0, "frequency_0_V_we0");
    sc_trace(mVcdFile, frequency_0_V_d0, "frequency_0_V_d0");
    sc_trace(mVcdFile, frequency_0_V_q0, "frequency_0_V_q0");
    sc_trace(mVcdFile, frequency_0_V_address1, "frequency_0_V_address1");
    sc_trace(mVcdFile, frequency_0_V_ce1, "frequency_0_V_ce1");
    sc_trace(mVcdFile, frequency_0_V_q1, "frequency_0_V_q1");
    sc_trace(mVcdFile, frequency_1_V_address0, "frequency_1_V_address0");
    sc_trace(mVcdFile, frequency_1_V_ce0, "frequency_1_V_ce0");
    sc_trace(mVcdFile, frequency_1_V_we0, "frequency_1_V_we0");
    sc_trace(mVcdFile, frequency_1_V_d0, "frequency_1_V_d0");
    sc_trace(mVcdFile, frequency_1_V_q0, "frequency_1_V_q0");
    sc_trace(mVcdFile, frequency_1_V_address1, "frequency_1_V_address1");
    sc_trace(mVcdFile, frequency_1_V_ce1, "frequency_1_V_ce1");
    sc_trace(mVcdFile, frequency_1_V_q1, "frequency_1_V_q1");
    sc_trace(mVcdFile, s_frequency_V_1_reg_245, "s_frequency_V_1_reg_245");
    sc_trace(mVcdFile, ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4, "ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4");
    sc_trace(mVcdFile, ap_predicate_op127_read_state7, "ap_predicate_op127_read_state7");
    sc_trace(mVcdFile, ap_predicate_op128_read_state7, "ap_predicate_op128_read_state7");
    sc_trace(mVcdFile, ap_block_state7, "ap_block_state7");
    sc_trace(mVcdFile, s_value_V_1_reg_255, "s_value_V_1_reg_255");
    sc_trace(mVcdFile, ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4, "ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4");
    sc_trace(mVcdFile, node_freq_V_reg_265, "node_freq_V_reg_265");
    sc_trace(mVcdFile, ap_phi_mux_s_1_2_i_i_phi_fu_441_p4, "ap_phi_mux_s_1_2_i_i_phi_fu_441_p4");
    sc_trace(mVcdFile, s_0_0_i_i_reg_275, "s_0_0_i_i_reg_275");
    sc_trace(mVcdFile, ap_phi_mux_s_0_2_i_i_phi_fu_454_p4, "ap_phi_mux_s_0_2_i_i_phi_fu_454_p4");
    sc_trace(mVcdFile, t_V_2_reg_286, "t_V_2_reg_286");
    sc_trace(mVcdFile, ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4, "ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4");
    sc_trace(mVcdFile, t_V_reg_298, "t_V_reg_298");
    sc_trace(mVcdFile, ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4, "ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4");
    sc_trace(mVcdFile, op_assign_reg_310, "op_assign_reg_310");
    sc_trace(mVcdFile, s_frequency_V_2_reg_323, "s_frequency_V_2_reg_323");
    sc_trace(mVcdFile, s_value_V_2_reg_334, "s_value_V_2_reg_334");
    sc_trace(mVcdFile, s_1_1_i_i_reg_345, "s_1_1_i_i_reg_345");
    sc_trace(mVcdFile, s_0_1_i_i_reg_357, "s_0_1_i_i_reg_357");
    sc_trace(mVcdFile, t_V_4_reg_370, "t_V_4_reg_370");
    sc_trace(mVcdFile, t_V_3_reg_381, "t_V_3_reg_381");
    sc_trace(mVcdFile, p_0195_0_i_i_reg_392, "p_0195_0_i_i_reg_392");
    sc_trace(mVcdFile, p_0120_0_i_i_reg_402, "p_0120_0_i_i_reg_402");
    sc_trace(mVcdFile, s_next_1_2_i_i_reg_411, "s_next_1_2_i_i_reg_411");
    sc_trace(mVcdFile, s_next_0_2_i_i_reg_424, "s_next_0_2_i_i_reg_424");
    sc_trace(mVcdFile, s_1_2_i_i_reg_437, "s_1_2_i_i_reg_437");
    sc_trace(mVcdFile, s_0_2_i_i_reg_450, "s_0_2_i_i_reg_450");
    sc_trace(mVcdFile, p_0217_2_i_i_reg_463, "p_0217_2_i_i_reg_463");
    sc_trace(mVcdFile, in_count_V_1_fu_722_p2, "in_count_V_1_fu_722_p2");
    sc_trace(mVcdFile, p_0247_2_i_i_reg_475, "p_0247_2_i_i_reg_475");
    sc_trace(mVcdFile, zext_ln31_fu_531_p1, "zext_ln31_fu_531_p1");
    sc_trace(mVcdFile, zext_ln32_fu_557_p1, "zext_ln32_fu_557_p1");
    sc_trace(mVcdFile, zext_ln544_fu_563_p1, "zext_ln544_fu_563_p1");
    sc_trace(mVcdFile, zext_ln321_1_fu_687_p1, "zext_ln321_1_fu_687_p1");
    sc_trace(mVcdFile, zext_ln544_4_fu_693_p1, "zext_ln544_4_fu_693_p1");
    sc_trace(mVcdFile, zext_ln321_fu_716_p1, "zext_ln321_fu_716_p1");
    sc_trace(mVcdFile, zext_ln544_3_fu_729_p1, "zext_ln544_3_fu_729_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, trunc_ln321_1_fu_683_p1, "trunc_ln321_1_fu_683_p1");
    sc_trace(mVcdFile, add_ln209_1_fu_675_p2, "add_ln209_1_fu_675_p2");
    sc_trace(mVcdFile, trunc_ln321_fu_712_p1, "trunc_ln321_fu_712_p1");
    sc_trace(mVcdFile, add_ln209_fu_704_p2, "add_ln209_fu_704_p2");
    sc_trace(mVcdFile, extLd_cast_fu_497_p1, "extLd_cast_fu_497_p1");
    sc_trace(mVcdFile, zext_ln243_fu_506_p1, "zext_ln243_fu_506_p1");
    sc_trace(mVcdFile, lshr_ln_fu_521_p4, "lshr_ln_fu_521_p4");
    sc_trace(mVcdFile, zext_ln215_fu_537_p1, "zext_ln215_fu_537_p1");
    sc_trace(mVcdFile, ret_V_fu_541_p2, "ret_V_fu_541_p2");
    sc_trace(mVcdFile, lshr_ln1_fu_547_p4, "lshr_ln1_fu_547_p4");
    sc_trace(mVcdFile, trunc_ln31_fu_568_p1, "trunc_ln31_fu_568_p1");
    sc_trace(mVcdFile, icmp_ln34_1_fu_593_p2, "icmp_ln34_1_fu_593_p2");
    sc_trace(mVcdFile, xor_ln34_fu_599_p2, "xor_ln34_fu_599_p2");
    sc_trace(mVcdFile, icmp_ln34_fu_588_p2, "icmp_ln34_fu_588_p2");
    sc_trace(mVcdFile, and_ln34_fu_605_p2, "and_ln34_fu_605_p2");
    sc_trace(mVcdFile, icmp_ln879_fu_611_p2, "icmp_ln879_fu_611_p2");
    sc_trace(mVcdFile, icmp_ln52_1_fu_645_p2, "icmp_ln52_1_fu_645_p2");
    sc_trace(mVcdFile, xor_ln52_fu_651_p2, "xor_ln52_fu_651_p2");
    sc_trace(mVcdFile, icmp_ln52_fu_640_p2, "icmp_ln52_fu_640_p2");
    sc_trace(mVcdFile, and_ln52_fu_657_p2, "and_ln52_fu_657_p2");
    sc_trace(mVcdFile, icmp_ln879_3_fu_663_p2, "icmp_ln879_3_fu_663_p2");
    sc_trace(mVcdFile, grp_fu_487_p4, "grp_fu_487_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_184, "ap_condition_184");
#endif

    }
}

create_tree::~create_tree() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete frequency_0_V_U;
    delete frequency_1_V_U;
}

void create_tree::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        node_freq_V_reg_265 = ap_phi_mux_s_1_2_i_i_phi_fu_441_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        node_freq_V_reg_265 = s_frequency_V_reg_746.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        op_assign_reg_310 = i_reg_770.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        op_assign_reg_310 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_condition_184.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(or_ln34_reg_806.read(), ap_const_lv1_0)) {
            p_0120_0_i_i_reg_402 = intermediate_freq_ne_reg_801.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) {
            p_0120_0_i_i_reg_402 = intermediate_freq_V_1_reg_795.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_condition_184.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(or_ln34_reg_806.read(), ap_const_lv1_0)) {
            p_0195_0_i_i_reg_392 = intermediate_freq_V_1_reg_795.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) {
            p_0195_0_i_i_reg_392 = node_freq_V_reg_265.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()))) {
        p_0217_2_i_i_reg_463 = tree_count_V_1_fu_698_p2.read();
    } else if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()) && 
                !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        p_0217_2_i_i_reg_463 = t_V_4_reg_370.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()))) {
        p_0247_2_i_i_reg_475 = t_V_3_reg_381.read();
    } else if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()) && 
                !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        p_0247_2_i_i_reg_475 = in_count_V_1_fu_722_p2.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        s_0_0_i_i_reg_275 = ap_phi_mux_s_0_2_i_i_phi_fu_454_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        s_0_0_i_i_reg_275 = s_value_V_reg_741.read();
    }
    if (esl_seteq<1,1,1>(ap_condition_184.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(or_ln34_reg_806.read(), ap_const_lv1_0)) {
            s_0_1_i_i_reg_357 = s_0_0_i_i_reg_275.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) {
            s_0_1_i_i_reg_357 = s_value_V_1_reg_255.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()))) {
        s_0_2_i_i_reg_450 = s_0_1_i_i_reg_357.read();
    } else if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()) && 
                !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        s_0_2_i_i_reg_450 = s_value_V_2_reg_334.read();
    }
    if (esl_seteq<1,1,1>(ap_condition_184.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(or_ln34_reg_806.read(), ap_const_lv1_0)) {
            s_1_1_i_i_reg_345 = node_freq_V_reg_265.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) {
            s_1_1_i_i_reg_345 = s_frequency_V_1_reg_245.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()))) {
        s_1_2_i_i_reg_437 = s_1_1_i_i_reg_345.read();
    } else if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()) && 
                !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        s_1_2_i_i_reg_437 = s_frequency_V_2_reg_323.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        s_frequency_V_1_reg_245 = ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        s_frequency_V_1_reg_245 = in_frequency_V_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_condition_184.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(or_ln34_reg_806.read(), ap_const_lv1_0)) {
            s_frequency_V_2_reg_323 = s_frequency_V_1_reg_245.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) {
            s_frequency_V_2_reg_323 = in_frequency_V_dout.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()))) {
        s_next_0_2_i_i_reg_424 = s_value_V_2_reg_334.read();
    } else if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()) && 
                !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        s_next_0_2_i_i_reg_424 = in_value_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()))) {
        s_next_1_2_i_i_reg_411 = s_frequency_V_2_reg_323.read();
    } else if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()) && 
                !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        s_next_1_2_i_i_reg_411 = in_frequency_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        s_value_V_1_reg_255 = ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        s_value_V_1_reg_255 = in_value_V_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_condition_184.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(or_ln34_reg_806.read(), ap_const_lv1_0)) {
            s_value_V_2_reg_334 = s_value_V_1_reg_255.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) {
            s_value_V_2_reg_334 = in_value_V_dout.read();
        }
    }
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        t_V_2_reg_286 = ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        t_V_2_reg_286 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_condition_184.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(or_ln34_reg_806.read(), ap_const_lv1_0)) {
            t_V_3_reg_381 = t_V_reg_298.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) {
            t_V_3_reg_381 = in_count_V_fu_634_p2.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_condition_184.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(or_ln34_reg_806.read(), ap_const_lv1_0)) {
            t_V_4_reg_370 = tree_count_V_fu_628_p2.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) {
            t_V_4_reg_370 = t_V_2_reg_286.read();
        }
    }
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
        t_V_reg_298 = ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        t_V_reg_298 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        add_ln21_reg_761 = add_ln21_fu_500_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        extLd_loc_read_reg_734 = extLd_loc_dout.read();
        s_frequency_V_reg_746 = in_frequency_V_dout.read();
        s_value_V_reg_741 = in_value_V_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_770 = i_fu_515_p2.read();
        icmp_ln21_reg_766 = icmp_ln21_fu_510_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        intermediate_freq_V_1_reg_795 = intermediate_freq_V_1_fu_572_p3.read();
        intermediate_freq_ne_reg_801 = intermediate_freq_ne_fu_580_p3.read();
        or_ln34_reg_806 = or_ln34_fu_617_p2.read();
        zext_ln36_reg_810 = zext_ln36_fu_623_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        or_ln52_reg_840 = or_ln52_fu_669_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op78_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state5.read()))))) {
        right_V_addr_reg_835 =  (sc_lv<8>) (zext_ln36_reg_810.read());
    }
}

void create_tree::thread_add_ln209_1_fu_675_p2() {
    add_ln209_1_fu_675_p2 = (!p_0195_0_i_i_reg_392.read().is_01() || !p_0120_0_i_i_reg_402.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_0195_0_i_i_reg_392.read()) + sc_biguint<32>(p_0120_0_i_i_reg_402.read()));
}

void create_tree::thread_add_ln209_fu_704_p2() {
    add_ln209_fu_704_p2 = (!p_0195_0_i_i_reg_392.read().is_01() || !s_1_1_i_i_reg_345.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_0195_0_i_i_reg_392.read()) + sc_biguint<32>(s_1_1_i_i_reg_345.read()));
}

void create_tree::thread_add_ln21_fu_500_p2() {
    add_ln21_fu_500_p2 = (!extLd_cast_fu_497_p1.read().is_01() || !ap_const_lv10_3FF.is_01())? sc_lv<10>(): (sc_biguint<10>(extLd_cast_fu_497_p1.read()) + sc_bigint<10>(ap_const_lv10_3FF));
}

void create_tree::thread_and_ln34_fu_605_p2() {
    and_ln34_fu_605_p2 = (xor_ln34_fu_599_p2.read() & icmp_ln34_fu_588_p2.read());
}

void create_tree::thread_and_ln52_fu_657_p2() {
    and_ln52_fu_657_p2 = (xor_ln52_fu_651_p2.read() & icmp_ln52_fu_640_p2.read());
}

void create_tree::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void create_tree::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void create_tree::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void create_tree::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void create_tree::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void create_tree::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void create_tree::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void create_tree::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void create_tree::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()));
}

void create_tree::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()));
}

void create_tree::thread_ap_block_state5() {
    ap_block_state5 = ((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op78_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state5.read())));
}

void create_tree::thread_ap_block_state7() {
    ap_block_state7 = ((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read())));
}

void create_tree::thread_ap_condition_184() {
    ap_condition_184 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op78_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state5.read()))));
}

void create_tree::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void create_tree::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void create_tree::thread_ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()))) {
        ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4 = t_V_4_reg_370.read();
    } else {
        ap_phi_mux_p_0217_2_i_i_phi_fu_467_p4 = p_0217_2_i_i_reg_463.read();
    }
}

void create_tree::thread_ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()))) {
        ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4 = in_count_V_1_fu_722_p2.read();
    } else {
        ap_phi_mux_p_0247_2_i_i_phi_fu_479_p4 = p_0247_2_i_i_reg_475.read();
    }
}

void create_tree::thread_ap_phi_mux_s_0_2_i_i_phi_fu_454_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()))) {
        ap_phi_mux_s_0_2_i_i_phi_fu_454_p4 = s_value_V_2_reg_334.read();
    } else {
        ap_phi_mux_s_0_2_i_i_phi_fu_454_p4 = s_0_2_i_i_reg_450.read();
    }
}

void create_tree::thread_ap_phi_mux_s_1_2_i_i_phi_fu_441_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()))) {
        ap_phi_mux_s_1_2_i_i_phi_fu_441_p4 = s_frequency_V_2_reg_323.read();
    } else {
        ap_phi_mux_s_1_2_i_i_phi_fu_441_p4 = s_1_2_i_i_reg_437.read();
    }
}

void create_tree::thread_ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()))) {
        ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4 = in_value_V_dout.read();
    } else {
        ap_phi_mux_s_next_0_2_i_i_phi_fu_428_p4 = s_next_0_2_i_i_reg_424.read();
    }
}

void create_tree::thread_ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()))) {
        ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4 = in_frequency_V_dout.read();
    } else {
        ap_phi_mux_s_next_1_2_i_i_phi_fu_415_p4 = s_next_1_2_i_i_reg_411.read();
    }
}

void create_tree::thread_ap_predicate_op127_read_state7() {
    ap_predicate_op127_read_state7 = (esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()));
}

void create_tree::thread_ap_predicate_op128_read_state7() {
    ap_predicate_op128_read_state7 = (esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read()));
}

void create_tree::thread_ap_predicate_op78_read_state5() {
    ap_predicate_op78_read_state5 = (esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read()));
}

void create_tree::thread_ap_predicate_op79_read_state5() {
    ap_predicate_op79_read_state5 = (esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read()));
}

void create_tree::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void create_tree::thread_extLd_cast_fu_497_p1() {
    extLd_cast_fu_497_p1 = esl_zext<10,9>(extLd_loc_read_reg_734.read());
}

void create_tree::thread_extLd_loc_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        extLd_loc_blk_n = extLd_loc_empty_n.read();
    } else {
        extLd_loc_blk_n = ap_const_logic_1;
    }
}

void create_tree::thread_extLd_loc_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        extLd_loc_out_blk_n = extLd_loc_out_full_n.read();
    } else {
        extLd_loc_out_blk_n = ap_const_logic_1;
    }
}

void create_tree::thread_extLd_loc_out_din() {
    extLd_loc_out_din = extLd_loc_dout.read();
}

void create_tree::thread_extLd_loc_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        extLd_loc_out_write = ap_const_logic_1;
    } else {
        extLd_loc_out_write = ap_const_logic_0;
    }
}

void create_tree::thread_extLd_loc_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
        extLd_loc_read = ap_const_logic_1;
    } else {
        extLd_loc_read = ap_const_logic_0;
    }
}

void create_tree::thread_frequency_0_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_fu_712_p1.read()))) {
        frequency_0_V_address0 =  (sc_lv<7>) (zext_ln321_fu_716_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_1_fu_683_p1.read()))) {
        frequency_0_V_address0 =  (sc_lv<7>) (zext_ln321_1_fu_687_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        frequency_0_V_address0 =  (sc_lv<7>) (zext_ln31_fu_531_p1.read());
    } else {
        frequency_0_V_address0 = "XXXXXXX";
    }
}

void create_tree::thread_frequency_0_V_address1() {
    frequency_0_V_address1 =  (sc_lv<7>) (zext_ln32_fu_557_p1.read());
}

void create_tree::thread_frequency_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_1_fu_683_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_fu_712_p1.read())))) {
        frequency_0_V_ce0 = ap_const_logic_1;
    } else {
        frequency_0_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_frequency_0_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        frequency_0_V_ce1 = ap_const_logic_1;
    } else {
        frequency_0_V_ce1 = ap_const_logic_0;
    }
}

void create_tree::thread_frequency_0_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_fu_712_p1.read()))) {
            frequency_0_V_d0 = add_ln209_fu_704_p2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_1_fu_683_p1.read()))) {
            frequency_0_V_d0 = add_ln209_1_fu_675_p2.read();
        } else {
            frequency_0_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        frequency_0_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void create_tree::thread_frequency_0_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_1_fu_683_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln321_fu_712_p1.read())))) {
        frequency_0_V_we0 = ap_const_logic_1;
    } else {
        frequency_0_V_we0 = ap_const_logic_0;
    }
}

void create_tree::thread_frequency_1_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_fu_712_p1.read()))) {
        frequency_1_V_address0 =  (sc_lv<7>) (zext_ln321_fu_716_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_1_fu_683_p1.read()))) {
        frequency_1_V_address0 =  (sc_lv<7>) (zext_ln321_1_fu_687_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        frequency_1_V_address0 =  (sc_lv<7>) (zext_ln31_fu_531_p1.read());
    } else {
        frequency_1_V_address0 = "XXXXXXX";
    }
}

void create_tree::thread_frequency_1_V_address1() {
    frequency_1_V_address1 =  (sc_lv<7>) (zext_ln32_fu_557_p1.read());
}

void create_tree::thread_frequency_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_1_fu_683_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_fu_712_p1.read())))) {
        frequency_1_V_ce0 = ap_const_logic_1;
    } else {
        frequency_1_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_frequency_1_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        frequency_1_V_ce1 = ap_const_logic_1;
    } else {
        frequency_1_V_ce1 = ap_const_logic_0;
    }
}

void create_tree::thread_frequency_1_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_fu_712_p1.read()))) {
            frequency_1_V_d0 = add_ln209_fu_704_p2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_1_fu_683_p1.read()))) {
            frequency_1_V_d0 = add_ln209_1_fu_675_p2.read();
        } else {
            frequency_1_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        frequency_1_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void create_tree::thread_frequency_1_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_1_fu_683_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln321_fu_712_p1.read())))) {
        frequency_1_V_we0 = ap_const_logic_1;
    } else {
        frequency_1_V_we0 = ap_const_logic_0;
    }
}

void create_tree::thread_grp_fu_487_p4() {
    grp_fu_487_p4 = op_assign_reg_310.read().range(8, 1);
}

void create_tree::thread_i_fu_515_p2() {
    i_fu_515_p2 = (!op_assign_reg_310.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(op_assign_reg_310.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void create_tree::thread_icmp_ln21_fu_510_p2() {
    icmp_ln21_fu_510_p2 = (!zext_ln243_fu_506_p1.read().is_01() || !add_ln21_reg_761.read().is_01())? sc_lv<1>(): (sc_bigint<10>(zext_ln243_fu_506_p1.read()) < sc_bigint<10>(add_ln21_reg_761.read()));
}

void create_tree::thread_icmp_ln34_1_fu_593_p2() {
    icmp_ln34_1_fu_593_p2 = (!intermediate_freq_V_1_fu_572_p3.read().is_01() || !node_freq_V_reg_265.read().is_01())? sc_lv<1>(): (sc_biguint<32>(intermediate_freq_V_1_fu_572_p3.read()) < sc_biguint<32>(node_freq_V_reg_265.read()));
}

void create_tree::thread_icmp_ln34_fu_588_p2() {
    icmp_ln34_fu_588_p2 = (!t_V_reg_298.read().is_01() || !extLd_loc_read_reg_734.read().is_01())? sc_lv<1>(): (sc_biguint<9>(t_V_reg_298.read()) < sc_biguint<9>(extLd_loc_read_reg_734.read()));
}

void create_tree::thread_icmp_ln52_1_fu_645_p2() {
    icmp_ln52_1_fu_645_p2 = (!p_0120_0_i_i_reg_402.read().is_01() || !s_1_1_i_i_reg_345.read().is_01())? sc_lv<1>(): (sc_biguint<32>(p_0120_0_i_i_reg_402.read()) < sc_biguint<32>(s_1_1_i_i_reg_345.read()));
}

void create_tree::thread_icmp_ln52_fu_640_p2() {
    icmp_ln52_fu_640_p2 = (!t_V_3_reg_381.read().is_01() || !extLd_loc_read_reg_734.read().is_01())? sc_lv<1>(): (sc_biguint<9>(t_V_3_reg_381.read()) < sc_biguint<9>(extLd_loc_read_reg_734.read()));
}

void create_tree::thread_icmp_ln879_3_fu_663_p2() {
    icmp_ln879_3_fu_663_p2 = (!t_V_4_reg_370.read().is_01() || !op_assign_reg_310.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_4_reg_370.read() == op_assign_reg_310.read());
}

void create_tree::thread_icmp_ln879_fu_611_p2() {
    icmp_ln879_fu_611_p2 = (!t_V_2_reg_286.read().is_01() || !op_assign_reg_310.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_2_reg_286.read() == op_assign_reg_310.read());
}

void create_tree::thread_in_count_V_1_fu_722_p2() {
    in_count_V_1_fu_722_p2 = (!t_V_3_reg_381.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(t_V_3_reg_381.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void create_tree::thread_in_count_V_fu_634_p2() {
    in_count_V_fu_634_p2 = (!t_V_reg_298.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(t_V_reg_298.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void create_tree::thread_in_frequency_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) || 
         (esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read())))) {
        in_frequency_V_blk_n = in_frequency_V_empty_n.read();
    } else {
        in_frequency_V_blk_n = ap_const_logic_1;
    }
}

void create_tree::thread_in_frequency_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state5.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op78_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state5.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read())))))) {
        in_frequency_V_read = ap_const_logic_1;
    } else {
        in_frequency_V_read = ap_const_logic_0;
    }
}

void create_tree::thread_in_value_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_reg_806.read())) || 
         (esl_seteq<1,1,1>(icmp_ln21_reg_766.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_reg_840.read())))) {
        in_value_V_blk_n = in_value_V_empty_n.read();
    } else {
        in_value_V_blk_n = ap_const_logic_1;
    }
}

void create_tree::thread_in_value_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op78_read_state5.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op78_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state5.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read())))))) {
        in_value_V_read = ap_const_logic_1;
    } else {
        in_value_V_read = ap_const_logic_0;
    }
}

void create_tree::thread_intermediate_freq_V_1_fu_572_p3() {
    intermediate_freq_V_1_fu_572_p3 = (!trunc_ln31_fu_568_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln31_fu_568_p1.read()[0].to_bool())? frequency_1_V_q0.read(): frequency_0_V_q0.read());
}

void create_tree::thread_intermediate_freq_ne_fu_580_p3() {
    intermediate_freq_ne_fu_580_p3 = (!trunc_ln31_fu_568_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln31_fu_568_p1.read()[0].to_bool())? frequency_0_V_q1.read(): frequency_1_V_q1.read());
}

void create_tree::thread_left_V_address0() {
    left_V_address0 =  (sc_lv<8>) (zext_ln36_fu_623_p1.read());
}

void create_tree::thread_left_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(or_ln34_fu_617_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_fu_617_p2.read())))) {
        left_V_ce0 = ap_const_logic_1;
    } else {
        left_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_left_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_fu_617_p2.read())) {
            left_V_d0 = s_0_0_i_i_reg_275.read();
        } else if (esl_seteq<1,1,1>(or_ln34_fu_617_p2.read(), ap_const_lv1_0)) {
            left_V_d0 = ap_const_lv9_1FF;
        } else {
            left_V_d0 =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        left_V_d0 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void create_tree::thread_left_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(or_ln34_fu_617_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln34_fu_617_p2.read())))) {
        left_V_we0 = ap_const_logic_1;
    } else {
        left_V_we0 = ap_const_logic_0;
    }
}

void create_tree::thread_lshr_ln1_fu_547_p4() {
    lshr_ln1_fu_547_p4 = ret_V_fu_541_p2.read().range(9, 1);
}

void create_tree::thread_lshr_ln_fu_521_p4() {
    lshr_ln_fu_521_p4 = t_V_2_reg_286.read().range(8, 1);
}

void create_tree::thread_or_ln34_fu_617_p2() {
    or_ln34_fu_617_p2 = (and_ln34_fu_605_p2.read() | icmp_ln879_fu_611_p2.read());
}

void create_tree::thread_or_ln52_fu_669_p2() {
    or_ln52_fu_669_p2 = (and_ln52_fu_657_p2.read() | icmp_ln879_3_fu_663_p2.read());
}

void create_tree::thread_parent_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        parent_V_address0 =  (sc_lv<8>) (zext_ln544_3_fu_729_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        parent_V_address0 =  (sc_lv<8>) (zext_ln544_4_fu_693_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        parent_V_address0 =  (sc_lv<8>) (zext_ln544_fu_563_p1.read());
    } else {
        parent_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void create_tree::thread_parent_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        parent_V_ce0 = ap_const_logic_1;
    } else {
        parent_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_parent_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        parent_V_d0 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        parent_V_d0 = op_assign_reg_310.read();
    } else {
        parent_V_d0 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void create_tree::thread_parent_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(or_ln34_fu_617_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        parent_V_we0 = ap_const_logic_1;
    } else {
        parent_V_we0 = ap_const_logic_0;
    }
}

void create_tree::thread_ret_V_fu_541_p2() {
    ret_V_fu_541_p2 = (!ap_const_lv10_1.is_01() || !zext_ln215_fu_537_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_1) + sc_biguint<10>(zext_ln215_fu_537_p1.read()));
}

void create_tree::thread_right_V_address0() {
    right_V_address0 = right_V_addr_reg_835.read();
}

void create_tree::thread_right_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read())))) {
        right_V_ce0 = ap_const_logic_1;
    } else {
        right_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_right_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read())) {
            right_V_d0 = s_0_1_i_i_reg_357.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read())) {
            right_V_d0 = ap_const_lv9_1FF;
        } else {
            right_V_d0 =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        right_V_d0 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void create_tree::thread_right_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln52_fu_669_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, or_ln52_fu_669_p2.read())))) {
        right_V_we0 = ap_const_logic_1;
    } else {
        right_V_we0 = ap_const_logic_0;
    }
}

void create_tree::thread_tree_count_V_1_fu_698_p2() {
    tree_count_V_1_fu_698_p2 = (!t_V_4_reg_370.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(t_V_4_reg_370.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void create_tree::thread_tree_count_V_fu_628_p2() {
    tree_count_V_fu_628_p2 = (!t_V_2_reg_286.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(t_V_2_reg_286.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void create_tree::thread_trunc_ln31_fu_568_p1() {
    trunc_ln31_fu_568_p1 = t_V_2_reg_286.read().range(1-1, 0);
}

void create_tree::thread_trunc_ln321_1_fu_683_p1() {
    trunc_ln321_1_fu_683_p1 = op_assign_reg_310.read().range(1-1, 0);
}

void create_tree::thread_trunc_ln321_fu_712_p1() {
    trunc_ln321_fu_712_p1 = op_assign_reg_310.read().range(1-1, 0);
}

void create_tree::thread_xor_ln34_fu_599_p2() {
    xor_ln34_fu_599_p2 = (icmp_ln34_1_fu_593_p2.read() ^ ap_const_lv1_1);
}

void create_tree::thread_xor_ln52_fu_651_p2() {
    xor_ln52_fu_651_p2 = (icmp_ln52_1_fu_645_p2.read() ^ ap_const_lv1_1);
}

void create_tree::thread_zext_ln215_fu_537_p1() {
    zext_ln215_fu_537_p1 = esl_zext<10,9>(t_V_2_reg_286.read());
}

void create_tree::thread_zext_ln243_fu_506_p1() {
    zext_ln243_fu_506_p1 = esl_zext<10,9>(op_assign_reg_310.read());
}

void create_tree::thread_zext_ln31_fu_531_p1() {
    zext_ln31_fu_531_p1 = esl_zext<64,8>(lshr_ln_fu_521_p4.read());
}

void create_tree::thread_zext_ln321_1_fu_687_p1() {
    zext_ln321_1_fu_687_p1 = esl_zext<64,8>(grp_fu_487_p4.read());
}

void create_tree::thread_zext_ln321_fu_716_p1() {
    zext_ln321_fu_716_p1 = esl_zext<64,8>(grp_fu_487_p4.read());
}

void create_tree::thread_zext_ln32_fu_557_p1() {
    zext_ln32_fu_557_p1 = esl_zext<64,9>(lshr_ln1_fu_547_p4.read());
}

void create_tree::thread_zext_ln36_fu_623_p1() {
    zext_ln36_fu_623_p1 = esl_zext<64,9>(op_assign_reg_310.read());
}

void create_tree::thread_zext_ln544_3_fu_729_p1() {
    zext_ln544_3_fu_729_p1 = esl_zext<64,9>(t_V_2_reg_286.read());
}

void create_tree::thread_zext_ln544_4_fu_693_p1() {
    zext_ln544_4_fu_693_p1 = esl_zext<64,9>(t_V_4_reg_370.read());
}

void create_tree::thread_zext_ln544_fu_563_p1() {
    zext_ln544_fu_563_p1 = esl_zext<64,9>(t_V_2_reg_286.read());
}

void create_tree::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, extLd_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln21_fu_510_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op78_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state5.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, in_value_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_read_state7.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, in_frequency_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op128_read_state7.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<8>) ("XXXXXXXX");
            break;
    }
}

}

