// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Loop_read_stream_pro_HH_
#define _Loop_read_stream_pro_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Loop_read_stream_pro : public sc_module {
    // Port declarations 46
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<48> > symbol_histogram_TDATA;
    sc_in< sc_logic > symbol_histogram_TVALID;
    sc_out< sc_logic > symbol_histogram_TREADY;
    sc_in< sc_lv<6> > symbol_histogram_TKEEP;
    sc_in< sc_lv<6> > symbol_histogram_TSTRB;
    sc_in< sc_lv<1> > symbol_histogram_TUSER;
    sc_in< sc_lv<1> > symbol_histogram_TLAST;
    sc_in< sc_lv<1> > symbol_histogram_TID;
    sc_in< sc_lv<1> > symbol_histogram_TDEST;
    sc_out< sc_lv<41> > stream_buffer_0_din;
    sc_in< sc_logic > stream_buffer_0_full_n;
    sc_out< sc_logic > stream_buffer_0_write;
    sc_out< sc_lv<8> > stream_buffer_1_address0;
    sc_out< sc_logic > stream_buffer_1_ce0;
    sc_out< sc_logic > stream_buffer_1_we0;
    sc_out< sc_lv<6> > stream_buffer_1_d0;
    sc_out< sc_lv<8> > stream_buffer_2_address0;
    sc_out< sc_logic > stream_buffer_2_ce0;
    sc_out< sc_logic > stream_buffer_2_we0;
    sc_out< sc_lv<6> > stream_buffer_2_d0;
    sc_out< sc_lv<8> > stream_buffer_3_address0;
    sc_out< sc_logic > stream_buffer_3_ce0;
    sc_out< sc_logic > stream_buffer_3_we0;
    sc_out< sc_lv<1> > stream_buffer_3_d0;
    sc_out< sc_lv<8> > stream_buffer_4_address0;
    sc_out< sc_logic > stream_buffer_4_ce0;
    sc_out< sc_logic > stream_buffer_4_we0;
    sc_out< sc_lv<1> > stream_buffer_4_d0;
    sc_out< sc_lv<8> > stream_buffer_5_address0;
    sc_out< sc_logic > stream_buffer_5_ce0;
    sc_out< sc_logic > stream_buffer_5_we0;
    sc_out< sc_lv<1> > stream_buffer_5_d0;
    sc_out< sc_lv<8> > stream_buffer_6_address0;
    sc_out< sc_logic > stream_buffer_6_ce0;
    sc_out< sc_logic > stream_buffer_6_we0;
    sc_out< sc_lv<1> > stream_buffer_6_d0;


    // Module declarations
    Loop_read_stream_pro(sc_module_name name);
    SC_HAS_PROCESS(Loop_read_stream_pro);

    ~Loop_read_stream_pro();

    sc_trace_file* mVcdFile;

    regslice_both<48>* regslice_both_symbol_histogram_V_data_V_U;
    regslice_both<6>* regslice_both_symbol_histogram_V_keep_V_U;
    regslice_both<6>* regslice_both_symbol_histogram_V_strb_V_U;
    regslice_both<1>* regslice_both_symbol_histogram_V_user_V_U;
    regslice_both<1>* regslice_both_symbol_histogram_V_last_V_U;
    regslice_both<1>* regslice_both_symbol_histogram_V_id_V_U;
    regslice_both<1>* regslice_both_symbol_histogram_V_dest_V_U;
    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > symbol_histogram_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln25_fu_188_p2;
    sc_signal< sc_logic > stream_buffer_0_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<1> > icmp_ln25_reg_248;
    sc_signal< sc_lv<9> > i_0_i_reg_177;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<9> > i_fu_194_p2;
    sc_signal< sc_lv<41> > tmp_data_V_fu_244_p1;
    sc_signal< sc_lv<41> > tmp_data_V_reg_257;
    sc_signal< bool > ap_block_state1;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< sc_lv<64> > zext_ln27_fu_200_p1;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_data_V_U_apdone_blk;
    sc_signal< sc_lv<48> > symbol_histogram_TDATA_int;
    sc_signal< sc_logic > symbol_histogram_TVALID_int;
    sc_signal< sc_logic > symbol_histogram_TREADY_int;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_data_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_keep_V_U_apdone_blk;
    sc_signal< sc_lv<6> > symbol_histogram_TKEEP_int;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_keep_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_strb_V_U_apdone_blk;
    sc_signal< sc_lv<6> > symbol_histogram_TSTRB_int;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_strb_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_user_V_U_apdone_blk;
    sc_signal< sc_lv<1> > symbol_histogram_TUSER_int;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_user_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_last_V_U_apdone_blk;
    sc_signal< sc_lv<1> > symbol_histogram_TLAST_int;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_last_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_id_V_U_apdone_blk;
    sc_signal< sc_lv<1> > symbol_histogram_TID_int;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_id_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_dest_V_U_apdone_blk;
    sc_signal< sc_lv<1> > symbol_histogram_TDEST_int;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_dest_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_symbol_histogram_V_dest_V_U_ack_in;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state4;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<9> ap_const_lv9_100;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state4();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_i_fu_194_p2();
    void thread_icmp_ln25_fu_188_p2();
    void thread_internal_ap_ready();
    void thread_real_start();
    void thread_start_out();
    void thread_start_write();
    void thread_stream_buffer_0_blk_n();
    void thread_stream_buffer_0_din();
    void thread_stream_buffer_0_write();
    void thread_stream_buffer_1_address0();
    void thread_stream_buffer_1_ce0();
    void thread_stream_buffer_1_d0();
    void thread_stream_buffer_1_we0();
    void thread_stream_buffer_2_address0();
    void thread_stream_buffer_2_ce0();
    void thread_stream_buffer_2_d0();
    void thread_stream_buffer_2_we0();
    void thread_stream_buffer_3_address0();
    void thread_stream_buffer_3_ce0();
    void thread_stream_buffer_3_d0();
    void thread_stream_buffer_3_we0();
    void thread_stream_buffer_4_address0();
    void thread_stream_buffer_4_ce0();
    void thread_stream_buffer_4_d0();
    void thread_stream_buffer_4_we0();
    void thread_stream_buffer_5_address0();
    void thread_stream_buffer_5_ce0();
    void thread_stream_buffer_5_d0();
    void thread_stream_buffer_5_we0();
    void thread_stream_buffer_6_address0();
    void thread_stream_buffer_6_ce0();
    void thread_stream_buffer_6_d0();
    void thread_stream_buffer_6_we0();
    void thread_symbol_histogram_TDATA_blk_n();
    void thread_symbol_histogram_TREADY();
    void thread_symbol_histogram_TREADY_int();
    void thread_tmp_data_V_fu_244_p1();
    void thread_zext_ln27_fu_200_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
